#include "web_server.h"
#include "app_config.h"
#include "cooling_control.h"
#include "hardware_map.h"
#include "nvs_store.h"
#include "pump_control.h"
#include "session.h"
#include "wifi_manager.h"
#include "dns_server.h"
#include "esp_http_server.h"
#include "esp_wifi.h"
#include "esp_system.h"
#include "esp_chip_info.h"
#include "esp_mac.h"
#include "esp_heap_caps.h"
#include "esp_idf_version.h"
#include "esp_log.h"
#include "esp_timer.h"
#include "cJSON.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"

static const char *TAG = "web_server";

/* Embedded file declarations generated by EMBED_FILES in CMakeLists.txt */
extern const uint8_t _binary_login_html_start[] asm("_binary_login_html_start");
extern const uint8_t _binary_login_html_end[]   asm("_binary_login_html_end");
extern const uint8_t _binary_dashboard_html_start[] asm("_binary_dashboard_html_start");
extern const uint8_t _binary_dashboard_html_end[]   asm("_binary_dashboard_html_end");
extern const uint8_t _binary_wifi_html_start[] asm("_binary_wifi_html_start");
extern const uint8_t _binary_wifi_html_end[]   asm("_binary_wifi_html_end");
extern const uint8_t _binary_style_css_start[] asm("_binary_style_css_start");
extern const uint8_t _binary_style_css_end[]   asm("_binary_style_css_end");
extern const uint8_t _binary_app_js_start[] asm("_binary_app_js_start");
extern const uint8_t _binary_app_js_end[]   asm("_binary_app_js_end");
extern const uint8_t _binary_status_html_start[] asm("_binary_status_html_start");
extern const uint8_t _binary_status_html_end[]   asm("_binary_status_html_end");

/*
 * WARNING: Default credentials come from app_config.h.
 * These MUST be changed before any production deployment.
 * This is a local-prototype login system, not internet-facing security.
 */
#define DEFAULT_USERNAME APP_TEMPLATE_DEFAULT_USERNAME
#define DEFAULT_PASSWORD APP_TEMPLATE_DEFAULT_PASSWORD

#define RATE_LIMIT_MAX     APP_TEMPLATE_LOGIN_RATE_LIMIT_MAX
#define RATE_LIMIT_WINDOW  APP_TEMPLATE_LOGIN_RATE_LIMIT_SEC

static bool api_pump_add_status_object(cJSON *root);

/* --------------- Helpers --------------- */

static void url_decode(char *dst, const char *src)
{
    while (*src) {
        if (*src == '+') {
            *dst++ = ' ';
            src++;
        } else if (*src == '%' && src[1] && src[2]) {
            char hex[3] = {src[1], src[2], '\0'};
            *dst++ = (char)strtol(hex, NULL, 16);
            src += 3;
        } else {
            *dst++ = *src++;
        }
    }
    *dst = '\0';
}

/* Check that a string contains only printable UTF-8 characters (no control chars 0x00-0x1F except tab/newline) */
static bool is_valid_utf8_printable(const char *s, size_t max_len)
{
    if (!s || !s[0]) return false;
    size_t len = strnlen(s, max_len);
    if (len >= max_len) return false;
    for (size_t i = 0; i < len; i++) {
        unsigned char c = (unsigned char)s[i];
        if (c < 0x20 && c != '\t') return false;
    }
    return true;
}

/* Extract session token from Cookie header.
   WARNING: This is a local-prototype auth scheme.
   Session tokens are random but transmitted as plain cookies.
   Not secure against network sniffing on open Wi-Fi. */
static bool get_session_from_request(httpd_req_t *req, char *token_out, size_t token_len)
{
    size_t buf_len = httpd_req_get_hdr_value_len(req, "Cookie");
    if (buf_len <= 0) return false;

    char *cookie_buf = malloc(buf_len + 1);
    if (!cookie_buf) return false;

    if (httpd_req_get_hdr_value_str(req, "Cookie", cookie_buf, buf_len + 1) != ESP_OK) {
        free(cookie_buf);
        return false;
    }

    /* Simple parse: find "session=" */
    const char *start = strstr(cookie_buf, "session=");
    if (start) {
        start += 8; /* skip "session=" */
        const char *end = strchr(start, ';');
        size_t len = end ? (size_t)(end - start) : strlen(start);
        if (len >= token_len) len = token_len - 1;
        memcpy(token_out, start, len);
        token_out[len] = '\0';
        free(cookie_buf);
        return true;
    }
    free(cookie_buf);
    return false;
}

/* Auth check middleware - returns true if session is valid */
static bool require_auth(httpd_req_t *req)
{
    char token[SESSION_TOKEN_LEN] = {0};
    if (!get_session_from_request(req, token, sizeof(token))) return false;
    return session_validate(token);
}

/* Convert chip model enum to string */
static const char* chip_model_to_string(esp_chip_model_t model)
{
    switch (model) {
    case CHIP_ESP32:    return "ESP32";
    case CHIP_ESP32S2:  return "ESP32-S2";
    case CHIP_ESP32S3:  return "ESP32-S3";
    case CHIP_ESP32C2:  return "ESP32-C2";
    case CHIP_ESP32C3:  return "ESP32-C3";
    case CHIP_ESP32C5:  return "ESP32-C5";
    case CHIP_ESP32C6:  return "ESP32-C6";
    case CHIP_ESP32H2:  return "ESP32-H2";
    case CHIP_ESP32P4:  return "ESP32-P4";
    default:            return "Unknown";
    }
}

/* Format MAC address bytes to XX:XX:XX:XX:XX:XX string */
static void format_mac(const uint8_t *mac, char *out)
{
    snprintf(out, 18, "%02x:%02x:%02x:%02x:%02x:%02x",
             mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
}

static bool host_equals(const char *host_start, size_t host_len, const char *expected)
{
    return expected && strlen(expected) == host_len &&
           strncmp(host_start, expected, host_len) == 0;
}

static bool header_matches_allowed_origin(const char *header)
{
    if (!header || !header[0]) {
        return false;
    }

    const char *host_start = strstr(header, "://");
    host_start = host_start ? host_start + 3 : header;

    const char *host_end = host_start;
    while (*host_end && *host_end != ':' && *host_end != '/' &&
           *host_end != '?' && *host_end != '#') {
        host_end++;
    }

    size_t host_len = (size_t)(host_end - host_start);
    if (host_len == 0) {
        return false;
    }

    const char *ap_ip = wifi_manager_get_ap_ip();
    if (host_equals(host_start, host_len, ap_ip)) {
        return true;
    }

    const char *sta_ip = wifi_manager_get_sta_ip();
    if (sta_ip && sta_ip[0] && host_equals(host_start, host_len, sta_ip)) {
        return true;
    }

    return host_equals(host_start, host_len, APP_TEMPLATE_MDNS_HOSTNAME ".local");
}

/* Check Origin/Referer to prevent cross-site POST (CSRF mitigation) */
static bool is_same_origin(httpd_req_t *req, bool allow_missing_header)
{
    size_t buf_len = httpd_req_get_hdr_value_len(req, "Origin");
    char buf[128] = {0};

    if (buf_len > 0 && buf_len < sizeof(buf) - 1) {
        httpd_req_get_hdr_value_str(req, "Origin", buf, sizeof(buf));
    } else {
        buf_len = httpd_req_get_hdr_value_len(req, "Referer");
        if (buf_len > 0 && buf_len < sizeof(buf) - 1) {
            httpd_req_get_hdr_value_str(req, "Referer", buf, sizeof(buf));
        }
    }

    if (buf[0] == '\0') {
        ESP_LOGW(TAG, "POST request without Origin/Referer header");
        return allow_missing_header;
    }

    if (header_matches_allowed_origin(buf)) return true;

    ESP_LOGW(TAG, "Cross-origin POST blocked: %s", buf);
    return false;
}

/* Send JSON response */
static esp_err_t send_json(httpd_req_t *req, const char *json, const char *status)
{
    httpd_resp_set_type(req, "application/json");
    httpd_resp_set_status(req, status);
    httpd_resp_send(req, json, strlen(json));
    return ESP_OK;
}

static esp_err_t send_api_error(httpd_req_t *req, const char *code, const char *message,
                                const char *status)
{
    cJSON *root = cJSON_CreateObject();
    if (!root) {
        return send_json(req, "{\"ok\":false,\"error\":\"memory\",\"message\":\"JSON allocation failed\"}",
                         "500 Internal Server Error");
    }

    cJSON_AddBoolToObject(root, "ok", false);
    cJSON_AddStringToObject(root, "error", code);
    cJSON_AddStringToObject(root, "message", message);

    char *json_str = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    if (!json_str) {
        return send_json(req, "{\"ok\":false,\"error\":\"memory\",\"message\":\"JSON allocation failed\"}",
                         "500 Internal Server Error");
    }

    esp_err_t result = send_json(req, json_str, status);
    free(json_str);
    return result;
}

static esp_err_t send_api_error_with_pump_status(httpd_req_t *req, const char *code,
                                                 const char *message, const char *status)
{
    cJSON *root = cJSON_CreateObject();
    if (!root) {
        return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
    }

    cJSON_AddBoolToObject(root, "ok", false);
    cJSON_AddStringToObject(root, "error", code);
    cJSON_AddStringToObject(root, "message", message);
    api_pump_add_status_object(root);

    char *json_str = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    if (!json_str) {
        return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
    }

    esp_err_t result = send_json(req, json_str, status);
    free(json_str);
    return result;
}

static const char *api_pump_settings_status_name(nvs_store_pump_settings_load_status_t status)
{
    switch (status) {
    case NVS_STORE_PUMP_SETTINGS_LOADED:
        return "loaded";
    case NVS_STORE_PUMP_SETTINGS_DEFAULTS_MISSING:
        return "defaults_missing";
    case NVS_STORE_PUMP_SETTINGS_DEFAULTS_INVALID:
        return "defaults_invalid";
    case NVS_STORE_PUMP_SETTINGS_DEFAULTS_ERROR:
    default:
        return "defaults_error";
    }
}

static const char *api_hardware_map_status_name(nvs_store_hardware_map_load_status_t status)
{
    switch (status) {
    case NVS_STORE_HARDWARE_MAP_LOADED:
        return "loaded";
    case NVS_STORE_HARDWARE_MAP_DEFAULTS_MISSING:
        return "defaults_missing";
    case NVS_STORE_HARDWARE_MAP_DEFAULTS_INVALID:
        return "defaults_invalid";
    case NVS_STORE_HARDWARE_MAP_DEFAULTS_ERROR:
    default:
        return "defaults_error";
    }
}

static const char *api_pending_hardware_map_status_name(nvs_store_pending_hardware_map_load_status_t status)
{
    switch (status) {
    case NVS_STORE_PENDING_HARDWARE_MAP_LOADED:
        return "loaded";
    case NVS_STORE_PENDING_HARDWARE_MAP_NOT_FOUND:
        return "not_found";
    case NVS_STORE_PENDING_HARDWARE_MAP_INVALID:
        return "invalid";
    case NVS_STORE_PENDING_HARDWARE_MAP_ERROR:
    default:
        return "error";
    }
}

static const char *api_hardware_map_field_for_role(hardware_role_t role)
{
    switch (role) {
    case HARDWARE_ROLE_FLOAT_INPUT:
        return "float_input_gpio";
    case HARDWARE_ROLE_PUMP_RELAY_1:
        return "pump_relay1_gpio";
    case HARDWARE_ROLE_PUMP_RELAY_2:
        return "pump_relay2_gpio";
    case HARDWARE_ROLE_DS18B20_DATA:
        return "ds18b20_gpio";
    case HARDWARE_ROLE_COOLING_RELAY:
        return "cooling_relay_gpio";
    default:
        return "unknown";
    }
}

static bool api_hardware_map_add_json(cJSON *root, const char *name, const hardware_map_t *map)
{
    if (!root || !name || !map) {
        return false;
    }

    cJSON *obj = cJSON_AddObjectToObject(root, name);
    if (!obj) {
        return false;
    }

    cJSON_AddNumberToObject(obj, "float_input_gpio", map->float_input_gpio);
    cJSON_AddNumberToObject(obj, "pump_relay1_gpio", map->pump_relay1_gpio);
    cJSON_AddNumberToObject(obj, "pump_relay2_gpio", map->pump_relay2_gpio);
    cJSON_AddNumberToObject(obj, "ds18b20_gpio", map->ds18b20_data_gpio);
    cJSON_AddNumberToObject(obj, "cooling_relay_gpio", map->cooling_relay_gpio);
    return true;
}

static bool api_hardware_options_add_role(cJSON *options_root, hardware_role_t role)
{
    if (!options_root || !hardware_map_role_valid(role)) {
        return false;
    }

    size_t option_count = 0;
    const hardware_gpio_option_t *options = hardware_map_options_for_role(role, &option_count);
    if (!options) {
        return false;
    }

    cJSON *arr = cJSON_AddArrayToObject(options_root, api_hardware_map_field_for_role(role));
    if (!arr) {
        return false;
    }

    for (size_t i = 0; i < option_count; i++) {
        cJSON *item = cJSON_CreateObject();
        if (!item) {
            return false;
        }
        cJSON_AddNumberToObject(item, "gpio", options[i].gpio);
        cJSON_AddStringToObject(item, "label", options[i].label);
        cJSON_AddStringToObject(item, "role", hardware_map_role_name(options[i].role));
        cJSON_AddBoolToObject(item, "input_capable", options[i].input_capable);
        cJSON_AddBoolToObject(item, "output_capable", options[i].output_capable);
        cJSON_AddBoolToObject(item, "internal_pull_capable", options[i].internal_pull_capable);
        cJSON_AddBoolToObject(item, "is_default", options[i].is_default);
        if (!cJSON_AddItemToArray(arr, item)) {
            cJSON_Delete(item);
            return false;
        }
    }

    return true;
}

static bool api_hardware_map_add_options(cJSON *root)
{
    if (!root) {
        return false;
    }

    cJSON *options = cJSON_AddObjectToObject(root, "options");
    if (!options) {
        return false;
    }

    for (hardware_role_t role = HARDWARE_ROLE_FLOAT_INPUT;
         role < HARDWARE_ROLE_COUNT;
         role = (hardware_role_t)(role + 1)) {
        if (!api_hardware_options_add_role(options, role)) {
            return false;
        }
    }

    return true;
}

static esp_err_t api_hardware_map_send(httpd_req_t *req)
{
    hardware_map_t active = hardware_map_defaults();
    hardware_map_t pending = hardware_map_defaults();
    nvs_store_hardware_map_load_status_t active_status = nvs_store_load_hardware_map(&active);
    nvs_store_pending_hardware_map_load_status_t pending_status =
        nvs_store_load_pending_hardware_map(&pending);

    bool pending_valid = pending_status == NVS_STORE_PENDING_HARDWARE_MAP_LOADED;
    bool reboot_required = false;
    bool reboot_status_ok = nvs_store_hardware_reboot_required(&reboot_required);
    if (!pending_valid) {
        reboot_required = false;
    }

    cJSON *root = cJSON_CreateObject();
    if (!root) {
        return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
    }

    cJSON_AddBoolToObject(root, "ok", true);
    cJSON_AddStringToObject(root, "active_status", api_hardware_map_status_name(active_status));
    cJSON_AddStringToObject(root, "pending_status",
                            api_pending_hardware_map_status_name(pending_status));
    cJSON_AddBoolToObject(root, "pending_valid", pending_valid);
    cJSON_AddBoolToObject(root, "reboot_required", reboot_status_ok && reboot_required);
    if (!api_hardware_map_add_json(root, "active", &active)) {
        cJSON_Delete(root);
        return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
    }
    if (pending_valid) {
        if (!api_hardware_map_add_json(root, "pending", &pending)) {
            cJSON_Delete(root);
            return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
        }
    } else {
        cJSON_AddNullToObject(root, "pending");
    }
    if (!api_hardware_map_add_options(root)) {
        cJSON_Delete(root);
        return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
    }

    char *json_str = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    if (!json_str) {
        return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
    }

    esp_err_t result = send_json(req, json_str, "200 OK");
    free(json_str);
    return result;
}

static const char *api_pump_relay_polarity_name(bool relay_active_low)
{
    return relay_active_low ? "active_low" : "active_high";
}

static bool api_pump_parse_relay_polarity(const cJSON *item, bool *relay_active_low)
{
    if (!item || !cJSON_IsString(item) || !relay_active_low) {
        return false;
    }
    if (strcmp(item->valuestring, "active_low") == 0) {
        *relay_active_low = true;
        return true;
    }
    if (strcmp(item->valuestring, "active_high") == 0) {
        *relay_active_low = false;
        return true;
    }
    return false;
}

static pump_control_relay_polarity_t api_pump_relay_polarity_from_bool(bool active_low)
{
    return active_low ? PUMP_CONTROL_RELAY_ACTIVE_LOW : PUMP_CONTROL_RELAY_ACTIVE_HIGH;
}

static pump_control_start_phase_t api_pump_start_phase_from_hardware(hardware_timer_start_phase_t phase)
{
    return phase == HARDWARE_TIMER_START_PHASE_OFF
        ? PUMP_CONTROL_START_PHASE_OFF
        : PUMP_CONTROL_START_PHASE_ON;
}

static bool api_pump_parse_start_phase(const cJSON *item, hardware_timer_start_phase_t *phase)
{
    if (!item || !cJSON_IsString(item) || !phase) {
        return false;
    }
    if (strcmp(item->valuestring, "on") == 0) {
        *phase = HARDWARE_TIMER_START_PHASE_ON;
        return true;
    }
    if (strcmp(item->valuestring, "off") == 0) {
        *phase = HARDWARE_TIMER_START_PHASE_OFF;
        return true;
    }
    return false;
}

static bool api_pump_load_active_hardware_map(hardware_map_t *map,
                                              nvs_store_hardware_map_load_status_t *status)
{
    if (!map || !status) {
        return false;
    }

    *status = nvs_store_load_hardware_map(map);
    return *status != NVS_STORE_HARDWARE_MAP_DEFAULTS_ERROR;
}

static void api_pump_settings_to_runtime_config(const nvs_store_pump_settings_t *settings,
                                                pump_control_config_t *config)
{
    if (!settings || !config) {
        return;
    }

    *config = pump_control_default_config();
    hardware_map_t active_map = hardware_map_defaults();
    nvs_store_hardware_map_load_status_t map_status = NVS_STORE_HARDWARE_MAP_DEFAULTS_MISSING;
    api_pump_load_active_hardware_map(&active_map, &map_status);
    config->float_gpio = active_map.float_input_gpio;
    config->relay_gpio = active_map.pump_relay1_gpio;
    config->relay1_gpio = active_map.pump_relay1_gpio;
    config->relay2_gpio = active_map.pump_relay2_gpio;
    config->timer1.on_sec = settings->timer1_on_sec;
    config->timer1.off_sec = settings->timer1_off_sec;
    config->timer2.on_sec = settings->timer2_on_sec;
    config->timer2.off_sec = settings->timer2_off_sec;
    config->relay_polarity = api_pump_relay_polarity_from_bool(settings->relay1_active_low);
    config->relay1_polarity = api_pump_relay_polarity_from_bool(settings->relay1_active_low);
    config->relay2_polarity = api_pump_relay_polarity_from_bool(settings->relay2_active_low);
    config->timer1_start_phase =
        api_pump_start_phase_from_hardware(settings->timer1_start_phase);
    config->timer2_start_phase =
        api_pump_start_phase_from_hardware(settings->timer2_start_phase);
}

static bool api_pump_add_config_fields(cJSON *root, const nvs_store_pump_settings_t *settings,
                                       nvs_store_pump_settings_load_status_t status)
{
    if (!root || !settings) {
        return false;
    }

    hardware_map_t active_map = hardware_map_defaults();
    nvs_store_hardware_map_load_status_t map_status = NVS_STORE_HARDWARE_MAP_DEFAULTS_MISSING;
    api_pump_load_active_hardware_map(&active_map, &map_status);
    bool hardware_reboot_required = false;
    bool hardware_reboot_status_ok = nvs_store_hardware_reboot_required(&hardware_reboot_required);
    nvs_store_cooling_settings_t cooling_settings;
    nvs_store_cooling_settings_defaults(&cooling_settings);
    nvs_store_load_cooling_settings(&cooling_settings);
    pump_control_config_t defaults = pump_control_default_config();
    cJSON_AddNumberToObject(root, "timer1_on_sec", settings->timer1_on_sec);
    cJSON_AddNumberToObject(root, "timer1_off_sec", settings->timer1_off_sec);
    cJSON_AddNumberToObject(root, "timer2_on_sec", settings->timer2_on_sec);
    cJSON_AddNumberToObject(root, "timer2_off_sec", settings->timer2_off_sec);
    cJSON_AddBoolToObject(root, "auto_start", settings->auto_start);
    cJSON_AddStringToObject(root, "relay_polarity",
                            api_pump_relay_polarity_name(settings->relay1_active_low));
    cJSON_AddNumberToObject(root, "float_gpio", active_map.float_input_gpio);
    cJSON_AddNumberToObject(root, "relay_gpio", active_map.pump_relay1_gpio);
    cJSON_AddNumberToObject(root, "debounce_ms", defaults.debounce_ms);
    cJSON_AddNumberToObject(root, "pump_relay1_gpio", active_map.pump_relay1_gpio);
    cJSON_AddNumberToObject(root, "pump_relay2_gpio", active_map.pump_relay2_gpio);
    cJSON_AddNumberToObject(root, "ds18b20_gpio", active_map.ds18b20_data_gpio);
    cJSON_AddNumberToObject(root, "cooling_relay_gpio", active_map.cooling_relay_gpio);
    cJSON_AddStringToObject(root, "relay1_polarity",
                            api_pump_relay_polarity_name(settings->relay1_active_low));
    cJSON_AddStringToObject(root, "relay2_polarity",
                            api_pump_relay_polarity_name(settings->relay2_active_low));
    cJSON_AddStringToObject(root, "timer1_start_phase",
                            hardware_map_timer_start_phase_name(settings->timer1_start_phase));
    cJSON_AddStringToObject(root, "timer2_start_phase",
                            hardware_map_timer_start_phase_name(settings->timer2_start_phase));
    cJSON_AddStringToObject(root, "cooling_relay_polarity",
                            hardware_map_polarity_name(cooling_settings.relay_polarity));
    cJSON_AddBoolToObject(root, "hardware_reboot_required",
                          hardware_reboot_status_ok && hardware_reboot_required);
    cJSON_AddBoolToObject(root, "hardware_fields_read_only", true);
    cJSON_AddStringToObject(root, "hardware_map_status", api_hardware_map_status_name(map_status));
    cJSON_AddStringToObject(root, "settings_status", api_pump_settings_status_name(status));
    return true;
}

static const char *api_pump_float_state_name(pump_control_float_state_t state)
{
    switch (state) {
    case PUMP_CONTROL_FLOAT_OFF:
        return "off";
    case PUMP_CONTROL_FLOAT_ON:
        return "on";
    case PUMP_CONTROL_FLOAT_UNKNOWN:
    default:
        return "unknown";
    }
}

static const char *api_pump_active_timer_name(pump_control_active_timer_t timer)
{
    switch (timer) {
    case PUMP_CONTROL_TIMER_1:
        return "timer1";
    case PUMP_CONTROL_TIMER_2:
        return "timer2";
    case PUMP_CONTROL_TIMER_NONE:
    default:
        return "none";
    }
}

static const char *api_pump_active_relay_name(pump_control_active_relay_t relay)
{
    switch (relay) {
    case PUMP_CONTROL_RELAY_1:
        return "relay1";
    case PUMP_CONTROL_RELAY_2:
        return "relay2";
    case PUMP_CONTROL_RELAY_NONE:
    default:
        return "none";
    }
}

static const char *api_pump_timer_phase_name(pump_control_timer_phase_t phase)
{
    switch (phase) {
    case PUMP_CONTROL_PHASE_ON:
        return "on";
    case PUMP_CONTROL_PHASE_OFF:
        return "off";
    case PUMP_CONTROL_PHASE_IDLE:
    default:
        return "idle";
    }
}

static const char *api_cooling_mode_name(cooling_control_mode_t mode)
{
    switch (mode) {
    case COOLING_CONTROL_MODE_AUTO:
        return "auto";
    case COOLING_CONTROL_MODE_TEST_ON:
        return "test_on";
    case COOLING_CONTROL_MODE_FORCE_OFF:
    default:
        return "force_off";
    }
}

static const char *api_cooling_settings_status_name(nvs_store_cooling_settings_load_status_t status)
{
    switch (status) {
    case NVS_STORE_COOLING_SETTINGS_LOADED:
        return "loaded";
    case NVS_STORE_COOLING_SETTINGS_DEFAULTS_MISSING:
        return "defaults_missing";
    case NVS_STORE_COOLING_SETTINGS_DEFAULTS_INVALID:
        return "defaults_invalid";
    case NVS_STORE_COOLING_SETTINGS_DEFAULTS_ERROR:
    default:
        return "defaults_error";
    }
}

static bool api_cooling_parse_mode(const cJSON *item, hardware_cooling_mode_t *mode)
{
    if (!item || !cJSON_IsString(item) || !mode) {
        return false;
    }
    if (strcmp(item->valuestring, "auto") == 0) {
        *mode = HARDWARE_COOLING_MODE_AUTO;
        return true;
    }
    if (strcmp(item->valuestring, "force_off") == 0) {
        *mode = HARDWARE_COOLING_MODE_FORCE_OFF;
        return true;
    }
    if (strcmp(item->valuestring, "test_on") == 0) {
        *mode = HARDWARE_COOLING_MODE_TEST_ON;
        return true;
    }
    return false;
}

static bool api_cooling_parse_polarity(const cJSON *item, hardware_relay_polarity_t *polarity)
{
    if (!item || !cJSON_IsString(item) || !polarity) {
        return false;
    }
    if (strcmp(item->valuestring, "active_low") == 0) {
        *polarity = HARDWARE_RELAY_ACTIVE_LOW;
        return true;
    }
    if (strcmp(item->valuestring, "active_high") == 0) {
        *polarity = HARDWARE_RELAY_ACTIVE_HIGH;
        return true;
    }
    return false;
}

static cooling_control_mode_t api_cooling_mode_from_hardware(hardware_cooling_mode_t mode)
{
    switch (mode) {
    case HARDWARE_COOLING_MODE_AUTO:
        return COOLING_CONTROL_MODE_AUTO;
    case HARDWARE_COOLING_MODE_TEST_ON:
        return COOLING_CONTROL_MODE_TEST_ON;
    case HARDWARE_COOLING_MODE_FORCE_OFF:
    default:
        return COOLING_CONTROL_MODE_FORCE_OFF;
    }
}

static cooling_control_relay_polarity_t api_cooling_polarity_from_hardware(
    hardware_relay_polarity_t polarity)
{
    return polarity == HARDWARE_RELAY_ACTIVE_LOW
        ? COOLING_CONTROL_RELAY_ACTIVE_LOW
        : COOLING_CONTROL_RELAY_ACTIVE_HIGH;
}

static const char *api_cooling_sensor_state_name(cooling_control_sensor_state_t state)
{
    switch (state) {
    case COOLING_CONTROL_SENSOR_OK:
        return "ok";
    case COOLING_CONTROL_SENSOR_FAULT:
        return "fault";
    case COOLING_CONTROL_SENSOR_UNKNOWN:
    default:
        return "unknown";
    }
}

static const char *api_cooling_fault_code_name(cooling_control_fault_code_t code)
{
    switch (code) {
    case COOLING_CONTROL_FAULT_READ_FAILED:
        return "read_failed";
    case COOLING_CONTROL_FAULT_OUT_OF_RANGE:
        return "out_of_range";
    case COOLING_CONTROL_FAULT_CONFIG_INVALID:
        return "config_invalid";
    case COOLING_CONTROL_FAULT_NONE:
    default:
        return "none";
    }
}

static const char *api_cooling_blocked_reason_name(cooling_control_blocked_reason_t reason)
{
    switch (reason) {
    case COOLING_CONTROL_BLOCKED_COMPRESSOR_LOCKOUT:
        return "compressor_lockout";
    case COOLING_CONTROL_BLOCKED_SENSOR_FAULT:
        return "sensor_fault";
    case COOLING_CONTROL_BLOCKED_FORCE_OFF:
        return "force_off";
    case COOLING_CONTROL_BLOCKED_CONFIG_INVALID:
        return "config_invalid";
    case COOLING_CONTROL_BLOCKED_NONE:
    default:
        return "none";
    }
}

static bool api_pump_add_status_fields(cJSON *root)
{
    if (!root) {
        return false;
    }

    pump_control_status_t status = {0};
    if (!pump_control_get_status(&status)) {
        return false;
    }

    nvs_store_pump_settings_t settings;
    nvs_store_pump_settings_load_status_t settings_status = nvs_store_load_pump_settings(&settings);
    hardware_map_t active_map = hardware_map_defaults();
    nvs_store_hardware_map_load_status_t map_status = NVS_STORE_HARDWARE_MAP_DEFAULTS_MISSING;
    api_pump_load_active_hardware_map(&active_map, &map_status);
    bool hardware_reboot_required = false;
    bool hardware_reboot_status_ok = nvs_store_hardware_reboot_required(&hardware_reboot_required);
    nvs_store_cooling_settings_t cooling_settings;
    nvs_store_cooling_settings_defaults(&cooling_settings);
    nvs_store_load_cooling_settings(&cooling_settings);

    cJSON_AddBoolToObject(root, "running", status.running);
    cJSON_AddBoolToObject(root, "initialized", status.initialized);
    cJSON_AddBoolToObject(root, "config_valid", status.config_valid);
    cJSON_AddBoolToObject(root, "initial_stabilizing", status.initial_stabilizing);
    cJSON_AddBoolToObject(root, "fault", status.fault);
    cJSON_AddStringToObject(root, "float_state", api_pump_float_state_name(status.float_state));
    cJSON_AddStringToObject(root, "active_timer", api_pump_active_timer_name(status.active_timer));
    cJSON_AddStringToObject(root, "active_relay", api_pump_active_relay_name(status.active_relay));
    cJSON_AddStringToObject(root, "phase", api_pump_timer_phase_name(status.phase));
    cJSON_AddNumberToObject(root, "countdown_sec", status.countdown_sec);
    cJSON_AddBoolToObject(root, "relay_energized", status.relay_energized);
    cJSON_AddBoolToObject(root, "relay1_energized", status.relay1_energized);
    cJSON_AddBoolToObject(root, "relay2_energized", status.relay2_energized);
    cJSON_AddNumberToObject(root, "float_gpio", status.float_gpio);
    cJSON_AddNumberToObject(root, "relay_gpio", active_map.pump_relay1_gpio);
    cJSON_AddNumberToObject(root, "active_relay_gpio", status.relay_gpio);
    cJSON_AddNumberToObject(root, "pump_relay1_gpio", active_map.pump_relay1_gpio);
    cJSON_AddNumberToObject(root, "pump_relay2_gpio", active_map.pump_relay2_gpio);
    cJSON_AddNumberToObject(root, "ds18b20_gpio", active_map.ds18b20_data_gpio);
    cJSON_AddNumberToObject(root, "cooling_relay_gpio", active_map.cooling_relay_gpio);
    cJSON_AddStringToObject(root, "relay1_polarity",
                            api_pump_relay_polarity_name(settings.relay1_active_low));
    cJSON_AddStringToObject(root, "relay2_polarity",
                            api_pump_relay_polarity_name(settings.relay2_active_low));
    cJSON_AddStringToObject(root, "cooling_relay_polarity",
                            hardware_map_polarity_name(cooling_settings.relay_polarity));
    cJSON_AddStringToObject(root, "timer1_start_phase",
                            hardware_map_timer_start_phase_name(settings.timer1_start_phase));
    cJSON_AddStringToObject(root, "timer2_start_phase",
                            hardware_map_timer_start_phase_name(settings.timer2_start_phase));
    cJSON_AddBoolToObject(root, "hardware_reboot_required",
                          hardware_reboot_status_ok && hardware_reboot_required);
    cJSON_AddStringToObject(root, "hardware_map_status", api_hardware_map_status_name(map_status));
    cJSON_AddBoolToObject(root, "auto_start", settings.auto_start);
    cJSON_AddStringToObject(root, "settings_status", api_pump_settings_status_name(settings_status));
    return true;
}

static bool api_cooling_add_status_fields(cJSON *root)
{
    if (!root) {
        return false;
    }

    cooling_control_status_t status = {0};
    if (!cooling_control_get_status(&status)) {
        return false;
    }

    cJSON_AddBoolToObject(root, "initialized", status.initialized);
    cJSON_AddBoolToObject(root, "config_valid", status.config_valid);
    cJSON_AddStringToObject(root, "mode", api_cooling_mode_name(status.mode));
    cJSON_AddBoolToObject(root, "auto_enable", status.auto_enable);
    cJSON_AddNumberToObject(root, "temperature_c", status.temperature_c);
    cJSON_AddBoolToObject(root, "temperature_valid", status.temperature_valid);
    cJSON_AddStringToObject(root, "sensor_state",
                            api_cooling_sensor_state_name(status.sensor_state));
    cJSON_AddBoolToObject(root, "fault", status.fault);
    cJSON_AddStringToObject(root, "fault_code",
                            api_cooling_fault_code_name(status.fault_code));
    cJSON_AddBoolToObject(root, "relay_energized", status.relay_energized);
    cJSON_AddNumberToObject(root, "threshold_c", (double)status.threshold_c_x10 / 10.0);
    cJSON_AddNumberToObject(root, "hysteresis_c", (double)status.hysteresis_c_x10 / 10.0);
    cJSON_AddBoolToObject(root, "lockout_active", status.lockout_active);
    cJSON_AddNumberToObject(root, "lockout_remaining_sec", status.lockout_remaining_sec);
    cJSON_AddNumberToObject(root, "test_remaining_sec", status.test_remaining_sec);
    cJSON_AddBoolToObject(root, "cooling_demand", status.cooling_demand);
    cJSON_AddStringToObject(root, "blocked_reason",
                            api_cooling_blocked_reason_name(status.blocked_reason));
    cJSON_AddNumberToObject(root, "ds18b20_gpio", status.ds18b20_gpio);
    cJSON_AddNumberToObject(root, "cooling_relay_gpio", status.cooling_relay_gpio);
    return true;
}

static bool api_cooling_add_config_fields(cJSON *root,
                                          const nvs_store_cooling_settings_t *settings,
                                          nvs_store_cooling_settings_load_status_t status)
{
    if (!root || !settings) {
        return false;
    }

    cJSON_AddStringToObject(root, "settings_status", api_cooling_settings_status_name(status));
    cJSON_AddNumberToObject(root, "threshold_c", (double)settings->threshold_c_x10 / 10.0);
    cJSON_AddNumberToObject(root, "threshold_c_x10", settings->threshold_c_x10);
    cJSON_AddNumberToObject(root, "hysteresis_c", (double)settings->hysteresis_c_x10 / 10.0);
    cJSON_AddNumberToObject(root, "hysteresis_c_x10", settings->hysteresis_c_x10);
    cJSON_AddBoolToObject(root, "auto_enable", settings->auto_enable);
    cJSON_AddStringToObject(root, "mode", hardware_map_cooling_mode_name(settings->mode));
    cJSON_AddNumberToObject(root, "test_timeout_sec", settings->test_timeout_sec);
    cJSON_AddNumberToObject(root, "compressor_min_off_sec", settings->compressor_min_off_sec);
    cJSON_AddStringToObject(root, "cooling_relay_polarity",
                            hardware_map_polarity_name(settings->relay_polarity));
    return true;
}

static bool api_cooling_add_limits(cJSON *root)
{
    if (!root) {
        return false;
    }

    cJSON *limits = cJSON_AddObjectToObject(root, "limits");
    if (!limits) {
        return false;
    }
    cJSON_AddNumberToObject(limits, "threshold_c_x10_min", -550);
    cJSON_AddNumberToObject(limits, "threshold_c_x10_max", 1250);
    cJSON_AddNumberToObject(limits, "hysteresis_c_x10_min", 1);
    cJSON_AddNumberToObject(limits, "hysteresis_c_x10_max", 500);
    cJSON_AddNumberToObject(limits, "test_timeout_sec_min", 1);
    cJSON_AddNumberToObject(limits, "test_timeout_sec_max", 3600);
    cJSON_AddNumberToObject(limits, "compressor_min_off_sec_min", 0);
    cJSON_AddNumberToObject(limits, "compressor_min_off_sec_max", 86400);

    cJSON *modes = cJSON_AddArrayToObject(root, "modes");
    cJSON *polarities = cJSON_AddArrayToObject(root, "relay_polarities");
    if (!modes || !polarities) {
        return false;
    }
    cJSON_AddItemToArray(modes, cJSON_CreateString("auto"));
    cJSON_AddItemToArray(modes, cJSON_CreateString("force_off"));
    cJSON_AddItemToArray(modes, cJSON_CreateString("test_on"));
    cJSON_AddItemToArray(polarities, cJSON_CreateString("active_low"));
    cJSON_AddItemToArray(polarities, cJSON_CreateString("active_high"));
    return true;
}

static void api_cooling_settings_to_runtime_config(const nvs_store_cooling_settings_t *settings,
                                                   cooling_control_config_t *config)
{
    if (!settings || !config) {
        return;
    }

    *config = cooling_control_default_config();
    hardware_map_t active_map = hardware_map_defaults();
    nvs_store_hardware_map_load_status_t map_status = nvs_store_load_hardware_map(&active_map);
    if (map_status == NVS_STORE_HARDWARE_MAP_DEFAULTS_ERROR) {
        return;
    }

    config->ds18b20_gpio = active_map.ds18b20_data_gpio;
    config->cooling_relay_gpio = active_map.cooling_relay_gpio;
    config->relay_polarity = api_cooling_polarity_from_hardware(settings->relay_polarity);
    config->threshold_c_x10 = settings->threshold_c_x10;
    config->hysteresis_c_x10 = settings->hysteresis_c_x10;
    config->auto_enable = settings->auto_enable;
    config->mode = api_cooling_mode_from_hardware(settings->mode);
    config->test_timeout_sec = settings->test_timeout_sec;
    config->compressor_min_off_sec = settings->compressor_min_off_sec;
}

static esp_err_t api_cooling_send_config(httpd_req_t *req,
                                         const nvs_store_cooling_settings_t *settings,
                                         nvs_store_cooling_settings_load_status_t status,
                                         bool include_status)
{
    cJSON *root = cJSON_CreateObject();
    if (!root) {
        return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
    }

    cJSON_AddBoolToObject(root, "ok", true);
    api_cooling_add_config_fields(root, settings, status);
    api_cooling_add_limits(root);
    if (include_status) {
        cJSON *status_obj = cJSON_AddObjectToObject(root, "status");
        if (!status_obj || !api_cooling_add_status_fields(status_obj)) {
            cJSON_Delete(root);
            return send_api_error(req, "status_unavailable", "Cooling status is unavailable",
                                  "409 Conflict");
        }
    }

    char *json_str = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    if (!json_str) {
        return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
    }

    esp_err_t result = send_json(req, json_str, "200 OK");
    free(json_str);
    return result;
}

static esp_err_t api_cooling_send_apply_error(httpd_req_t *req, const char *code,
                                              const char *message,
                                              const nvs_store_cooling_settings_t *settings)
{
    cJSON *root = cJSON_CreateObject();
    if (!root) {
        return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
    }

    cJSON_AddBoolToObject(root, "ok", false);
    cJSON_AddStringToObject(root, "error", code);
    cJSON_AddStringToObject(root, "message", message);
    api_cooling_add_config_fields(root, settings, NVS_STORE_COOLING_SETTINGS_LOADED);
    cJSON *status_obj = cJSON_AddObjectToObject(root, "status");
    if (status_obj) {
        api_cooling_add_status_fields(status_obj);
    }

    char *json_str = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    if (!json_str) {
        return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
    }

    esp_err_t result = send_json(req, json_str, "500 Internal Server Error");
    free(json_str);
    return result;
}

static bool api_pump_add_status_object(cJSON *root)
{
    cJSON *status_obj = cJSON_AddObjectToObject(root, "status");
    if (!status_obj) {
        return false;
    }
    return api_pump_add_status_fields(status_obj);
}

static bool api_pump_json_has_field(const cJSON *root, const char *name)
{
    return cJSON_GetObjectItem(root, name) != NULL;
}

static bool api_pump_required_u32(const cJSON *root, const char *name, uint32_t *out,
                                  const char **error_code, const char **error_message)
{
    const cJSON *item = cJSON_GetObjectItem(root, name);
    if (!item) {
        *error_code = "missing_field";
        *error_message = name;
        return false;
    }
    if (!cJSON_IsNumber(item) || !(item->valuedouble >= 0.0)) {
        *error_code = "invalid_type";
        *error_message = name;
        return false;
    }
    if (item->valuedouble < (double)APP_TEMPLATE_PUMP_TIMER_MIN_SEC ||
        item->valuedouble > (double)APP_TEMPLATE_PUMP_TIMER_MAX_SEC) {
        *error_code = "duration_out_of_range";
        *error_message = name;
        return false;
    }

    uint32_t value = (uint32_t)item->valuedouble;
    if ((double)value != item->valuedouble) {
        *error_code = "invalid_type";
        *error_message = name;
        return false;
    }

    *out = value;
    return true;
}

static bool api_pump_required_bool(const cJSON *root, const char *name, bool *out,
                                   const char **error_code, const char **error_message)
{
    const cJSON *item = cJSON_GetObjectItem(root, name);
    if (!item) {
        *error_code = "missing_field";
        *error_message = name;
        return false;
    }
    if (!cJSON_IsBool(item)) {
        *error_code = "invalid_type";
        *error_message = name;
        return false;
    }

    *out = cJSON_IsTrue(item);
    return true;
}

static bool api_hardware_required_gpio(const cJSON *root, const char *name,
                                       hardware_role_t role, gpio_num_t *out,
                                       const char **error_code, const char **error_message)
{
    const cJSON *item = cJSON_GetObjectItem(root, name);
    if (!item) {
        *error_code = "missing_field";
        *error_message = name;
        return false;
    }
    if (!cJSON_IsNumber(item) || item->valuedouble < 0.0) {
        *error_code = "invalid_type";
        *error_message = name;
        return false;
    }

    int gpio = item->valueint;
    if ((double)gpio != item->valuedouble) {
        *error_code = "invalid_type";
        *error_message = name;
        return false;
    }
    if (!hardware_map_gpio_allowed_for_role(role, (gpio_num_t)gpio)) {
        *error_code = "gpio_not_allowed";
        *error_message = name;
        return false;
    }

    *out = (gpio_num_t)gpio;
    return true;
}

static bool api_hardware_parse_map_payload(const cJSON *root, hardware_map_t *map,
                                           const char **error_code,
                                           const char **error_message)
{
    if (!root || !map) {
        *error_code = "invalid_json";
        *error_message = "Expected a JSON object";
        return false;
    }

    const cJSON *map_obj = cJSON_GetObjectItem(root, "map");
    if (!map_obj || !cJSON_IsObject(map_obj)) {
        *error_code = "missing_field";
        *error_message = "map";
        return false;
    }

    const cJSON *confirm = cJSON_GetObjectItem(root, "confirm_reboot_required");
    if (!confirm || !cJSON_IsBool(confirm) || !cJSON_IsTrue(confirm)) {
        *error_code = "confirmation_required";
        *error_message = "confirm_reboot_required";
        return false;
    }

    if (!api_hardware_required_gpio(map_obj, "float_input_gpio",
                                    HARDWARE_ROLE_FLOAT_INPUT,
                                    &map->float_input_gpio, error_code, error_message) ||
        !api_hardware_required_gpio(map_obj, "pump_relay1_gpio",
                                    HARDWARE_ROLE_PUMP_RELAY_1,
                                    &map->pump_relay1_gpio, error_code, error_message) ||
        !api_hardware_required_gpio(map_obj, "pump_relay2_gpio",
                                    HARDWARE_ROLE_PUMP_RELAY_2,
                                    &map->pump_relay2_gpio, error_code, error_message) ||
        !api_hardware_required_gpio(map_obj, "ds18b20_gpio",
                                    HARDWARE_ROLE_DS18B20_DATA,
                                    &map->ds18b20_data_gpio, error_code, error_message) ||
        !api_hardware_required_gpio(map_obj, "cooling_relay_gpio",
                                    HARDWARE_ROLE_COOLING_RELAY,
                                    &map->cooling_relay_gpio, error_code, error_message)) {
        return false;
    }

    if (!hardware_map_validate(map)) {
        *error_code = "invalid_hardware_map";
        *error_message = "map";
        return false;
    }

    return true;
}

static bool api_cooling_required_i32_range(const cJSON *root, const char *name,
                                           int32_t min_value, int32_t max_value,
                                           int32_t *out,
                                           const char **error_code,
                                           const char **error_message)
{
    const cJSON *item = cJSON_GetObjectItem(root, name);
    if (!item) {
        *error_code = "missing_field";
        *error_message = name;
        return false;
    }
    if (!cJSON_IsNumber(item)) {
        *error_code = "invalid_type";
        *error_message = name;
        return false;
    }

    int32_t value = item->valueint;
    if ((double)value != item->valuedouble) {
        *error_code = "invalid_type";
        *error_message = name;
        return false;
    }
    if (value < min_value || value > max_value) {
        *error_code = "value_out_of_range";
        *error_message = name;
        return false;
    }

    *out = value;
    return true;
}

static bool api_cooling_required_u32_range(const cJSON *root, const char *name,
                                           uint32_t min_value, uint32_t max_value,
                                           uint32_t *out,
                                           const char **error_code,
                                           const char **error_message)
{
    const cJSON *item = cJSON_GetObjectItem(root, name);
    if (!item) {
        *error_code = "missing_field";
        *error_message = name;
        return false;
    }
    if (!cJSON_IsNumber(item) || item->valuedouble < 0.0) {
        *error_code = "invalid_type";
        *error_message = name;
        return false;
    }

    uint32_t value = (uint32_t)item->valuedouble;
    if ((double)value != item->valuedouble) {
        *error_code = "invalid_type";
        *error_message = name;
        return false;
    }
    if (value < min_value || value > max_value) {
        *error_code = "value_out_of_range";
        *error_message = name;
        return false;
    }

    *out = value;
    return true;
}

static bool api_cooling_required_bool(const cJSON *root, const char *name, bool *out,
                                      const char **error_code, const char **error_message)
{
    const cJSON *item = cJSON_GetObjectItem(root, name);
    if (!item) {
        *error_code = "missing_field";
        *error_message = name;
        return false;
    }
    if (!cJSON_IsBool(item)) {
        *error_code = "invalid_type";
        *error_message = name;
        return false;
    }

    *out = cJSON_IsTrue(item);
    return true;
}

static bool api_cooling_parse_config_payload(const cJSON *root,
                                             nvs_store_cooling_settings_t *settings,
                                             const char **error_code,
                                             const char **error_message)
{
    if (!root || !settings) {
        *error_code = "invalid_json";
        *error_message = "Expected a JSON object";
        return false;
    }

    if (!api_cooling_required_i32_range(root, "threshold_c_x10", -550, 1250,
                                        &settings->threshold_c_x10,
                                        error_code, error_message) ||
        !api_cooling_required_i32_range(root, "hysteresis_c_x10", 1, 500,
                                        &settings->hysteresis_c_x10,
                                        error_code, error_message) ||
        !api_cooling_required_bool(root, "auto_enable", &settings->auto_enable,
                                   error_code, error_message) ||
        !api_cooling_required_u32_range(root, "test_timeout_sec", 1, 3600,
                                        &settings->test_timeout_sec,
                                        error_code, error_message) ||
        !api_cooling_required_u32_range(root, "compressor_min_off_sec", 0, 86400,
                                        &settings->compressor_min_off_sec,
                                        error_code, error_message)) {
        return false;
    }

    const cJSON *mode = cJSON_GetObjectItem(root, "mode");
    if (!api_cooling_parse_mode(mode, &settings->mode)) {
        *error_code = mode ? "invalid_cooling_mode" : "missing_field";
        *error_message = "mode";
        return false;
    }
    if (settings->mode == HARDWARE_COOLING_MODE_TEST_ON) {
        *error_code = "test_mode_not_persistent";
        *error_message = "Use /api/cooling/mode for runtime Test ON";
        return false;
    }

    const cJSON *polarity = cJSON_GetObjectItem(root, "cooling_relay_polarity");
    if (!api_cooling_parse_polarity(polarity, &settings->relay_polarity)) {
        *error_code = polarity ? "invalid_relay_polarity" : "missing_field";
        *error_message = "cooling_relay_polarity";
        return false;
    }

    return true;
}

static bool api_pump_parse_settings_payload(const cJSON *root,
                                            nvs_store_pump_settings_t *settings,
                                            const char **error_code,
                                            const char **error_message)
{
    if (!root || !settings) {
        *error_code = "invalid_json";
        *error_message = "Expected a JSON object";
        return false;
    }

    const char *readonly_fields[] = {
        "float_gpio",
        "relay_gpio",
        "debounce_ms",
        "pump_relay1_gpio",
        "pump_relay2_gpio",
        "ds18b20_gpio",
        "cooling_relay_gpio",
        "cooling_relay_polarity",
        "hardware_reboot_required"
    };
    for (size_t i = 0; i < sizeof(readonly_fields) / sizeof(readonly_fields[0]); i++) {
        if (api_pump_json_has_field(root, readonly_fields[i])) {
            *error_code = "read_only_field";
            *error_message = readonly_fields[i];
            return false;
        }
    }

    if (!api_pump_required_u32(root, "timer1_on_sec", &settings->timer1_on_sec,
                               error_code, error_message) ||
        !api_pump_required_u32(root, "timer1_off_sec", &settings->timer1_off_sec,
                               error_code, error_message) ||
        !api_pump_required_u32(root, "timer2_on_sec", &settings->timer2_on_sec,
                               error_code, error_message) ||
        !api_pump_required_u32(root, "timer2_off_sec", &settings->timer2_off_sec,
                               error_code, error_message) ||
        !api_pump_required_bool(root, "auto_start", &settings->auto_start,
                                error_code, error_message)) {
        return false;
    }

    const cJSON *relay1_polarity = cJSON_GetObjectItem(root, "relay1_polarity");
    const cJSON *legacy_polarity = cJSON_GetObjectItem(root, "relay_polarity");
    const cJSON *relay1_source = relay1_polarity ? relay1_polarity : legacy_polarity;
    if (!relay1_source) {
        *error_code = "missing_field";
        *error_message = "relay1_polarity";
        return false;
    }
    if (!api_pump_parse_relay_polarity(relay1_source, &settings->relay1_active_low)) {
        *error_code = "invalid_relay_polarity";
        *error_message = relay1_polarity ? "relay1_polarity" : "relay_polarity";
        return false;
    }
    settings->relay_active_low = settings->relay1_active_low;

    const cJSON *relay2_polarity = cJSON_GetObjectItem(root, "relay2_polarity");
    if (relay2_polarity &&
        !api_pump_parse_relay_polarity(relay2_polarity, &settings->relay2_active_low)) {
        *error_code = "invalid_relay_polarity";
        *error_message = "relay2_polarity";
        return false;
    }

    const cJSON *timer1_start = cJSON_GetObjectItem(root, "timer1_start_phase");
    if (!timer1_start) {
        *error_code = "missing_field";
        *error_message = "timer1_start_phase";
        return false;
    }
    if (!api_pump_parse_start_phase(timer1_start, &settings->timer1_start_phase) ||
        !hardware_map_timer_start_phase_valid(settings->timer1_start_phase)) {
        *error_code = "invalid_start_phase";
        *error_message = "timer1_start_phase";
        return false;
    }

    const cJSON *timer2_start = cJSON_GetObjectItem(root, "timer2_start_phase");
    if (!timer2_start) {
        *error_code = "missing_field";
        *error_message = "timer2_start_phase";
        return false;
    }
    if (!api_pump_parse_start_phase(timer2_start, &settings->timer2_start_phase) ||
        !hardware_map_timer_start_phase_valid(settings->timer2_start_phase)) {
        *error_code = "invalid_start_phase";
        *error_message = "timer2_start_phase";
        return false;
    }

    return true;
}

static esp_err_t api_pump_send_config(httpd_req_t *req,
                                      const nvs_store_pump_settings_t *settings,
                                      nvs_store_pump_settings_load_status_t status,
                                      bool include_status)
{
    cJSON *root = cJSON_CreateObject();
    if (!root) {
        return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
    }

    cJSON_AddBoolToObject(root, "ok", true);
    api_pump_add_config_fields(root, settings, status);
    if (include_status) {
        api_pump_add_status_object(root);
    }

    char *json_str = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    if (!json_str) {
        return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
    }

    esp_err_t result = send_json(req, json_str, "200 OK");
    free(json_str);
    return result;
}

/* Scan context for non-blocking callback */
typedef struct {
    SemaphoreHandle_t sem;
    wifi_scan_entry_t entries[WIFI_SCAN_MAX];
    int count;
} wifi_scan_ctx_t;

static void scan_complete_cb(void *user_ctx, wifi_scan_entry_t *entries, int count)
{
    wifi_scan_ctx_t *ctx = (wifi_scan_ctx_t *)user_ctx;
    ctx->count = (count > WIFI_SCAN_MAX) ? WIFI_SCAN_MAX : count;
    if (ctx->count > 0) {
        memcpy(ctx->entries, entries, ctx->count * sizeof(wifi_scan_entry_t));
    }
    xSemaphoreGive(ctx->sem);
}

/* Send a static embedded file */
static esp_err_t serve_static(httpd_req_t *req, const uint8_t *start, const uint8_t *end,
                              const char *mime_type)
{
    size_t len = (size_t)(end - start);
    httpd_resp_set_type(req, mime_type);
    httpd_resp_send(req, (const char *)start, len);
    return ESP_OK;
}

/* --------------- Route Handlers --------------- */

/* GET / - redirect based on auth status */
static esp_err_t handle_root(httpd_req_t *req)
{
    char token[SESSION_TOKEN_LEN] = {0};
    if (get_session_from_request(req, token, sizeof(token)) && session_validate(token)) {
        httpd_resp_set_status(req, "302 Found");
        httpd_resp_set_hdr(req, "Location", "/dashboard");
        httpd_resp_send(req, NULL, 0);
    } else {
        httpd_resp_set_status(req, "302 Found");
        httpd_resp_set_hdr(req, "Location", "/login");
        httpd_resp_send(req, NULL, 0);
    }
    return ESP_OK;
}

/* GET /login */
static esp_err_t handle_get_login(httpd_req_t *req)
{
    return serve_static(req,
        _binary_login_html_start, _binary_login_html_end,
        "text/html; charset=utf-8");
}

/* GET /dashboard - protected */
static esp_err_t handle_get_dashboard(httpd_req_t *req)
{
    if (!require_auth(req)) {
        httpd_resp_set_status(req, "302 Found");
        httpd_resp_set_hdr(req, "Location", "/login");
        httpd_resp_send(req, NULL, 0);
        return ESP_OK;
    }
    return serve_static(req,
        _binary_dashboard_html_start, _binary_dashboard_html_end,
        "text/html; charset=utf-8");
}

/* GET /wifi - protected */
static esp_err_t handle_get_wifi(httpd_req_t *req)
{
    if (!require_auth(req)) {
        httpd_resp_set_status(req, "302 Found");
        httpd_resp_set_hdr(req, "Location", "/login");
        httpd_resp_send(req, NULL, 0);
        return ESP_OK;
    }
    return serve_static(req,
        _binary_wifi_html_start, _binary_wifi_html_end,
        "text/html; charset=utf-8");
}

/* GET /style.css */
static esp_err_t handle_style_css(httpd_req_t *req)
{
    return serve_static(req,
        _binary_style_css_start, _binary_style_css_end,
        "text/css; charset=utf-8");
}

/* GET /app.js */
static esp_err_t handle_app_js(httpd_req_t *req)
{
    return serve_static(req,
        _binary_app_js_start, _binary_app_js_end,
        "application/javascript; charset=utf-8");
}

/* POST /api/login */
static esp_err_t handle_api_login(httpd_req_t *req)
{
    static int s_login_attempts = 0;
    static int64_t s_login_block_until = 0;

    if (!is_same_origin(req, true)) {
        return send_json(req, "{\"ok\":false,\"error\":\"forbidden\"}", "403 Forbidden");
    }

    int64_t now = esp_timer_get_time() / 1000000;
    if (s_login_block_until > now) {
        char resp[128];
        int remaining = (int)(s_login_block_until - now);
        snprintf(resp, sizeof(resp), "{\"ok\":false,\"error\":\"rate_limited\",\"retry_after\":%d}", remaining);
        return send_json(req, resp, "429 Too Many Requests");
    }

    char body[256] = {0};
    int ret = httpd_req_recv(req, body, sizeof(body) - 1);
    if (ret <= 0) {
        return send_json(req, "{\"ok\":false,\"error\":\"empty_body\"}", "401 Unauthorized");
    }
    body[ret] = '\0';

    char username[64] = {0};
    char password[64] = {0};

    const char *user_start = strstr(body, "username=");
    if (user_start) {
        user_start += 9;
        const char *user_end = strchr(user_start, '&');
        size_t len = user_end ? (size_t)(user_end - user_start) : strlen(user_start);
        if (len > sizeof(username) - 1) len = sizeof(username) - 1;
        char tmp[64] = {0};
        memcpy(tmp, user_start, len);
        url_decode(username, tmp);

        const char *pass_start = strstr(body, "password=");
        if (pass_start) {
            pass_start += 9;
            const char *pass_end = strchr(pass_start, '&');
            len = pass_end ? (size_t)(pass_end - pass_start) : strlen(pass_start);
            if (len > sizeof(password) - 1) len = sizeof(password) - 1;
            char tmp2[64] = {0};
            memcpy(tmp2, pass_start, len);
            url_decode(password, tmp2);
        }
    } else {
        cJSON *root = cJSON_Parse(body);
        if (root) {
            cJSON *u = cJSON_GetObjectItem(root, "username");
            cJSON *p = cJSON_GetObjectItem(root, "password");
            if (u && cJSON_IsString(u)) {
                strncpy(username, u->valuestring, sizeof(username) - 1);
            }
            if (p && cJSON_IsString(p)) {
                strncpy(password, p->valuestring, sizeof(password) - 1);
            }
            cJSON_Delete(root);
        }
    }

    if (strlen(username) == 0 || strlen(password) == 0) {
        s_login_attempts++;
        if (s_login_attempts >= RATE_LIMIT_MAX) {
            s_login_block_until = now + RATE_LIMIT_WINDOW;
        }
        return send_json(req, "{\"ok\":false,\"error\":\"missing_fields\"}", "401 Unauthorized");
    }

    if (!is_valid_utf8_printable(username, sizeof(username)) ||
        !is_valid_utf8_printable(password, sizeof(password))) {
        return send_json(req, "{\"ok\":false,\"error\":\"invalid_input\"}", "400 Bad Request");
    }

    if (strcmp(username, DEFAULT_USERNAME) != 0 || strcmp(password, DEFAULT_PASSWORD) != 0) {
        ESP_LOGW(TAG, "Login failed");
        s_login_attempts++;
        if (s_login_attempts >= RATE_LIMIT_MAX) {
            s_login_block_until = now + RATE_LIMIT_WINDOW;
        }
        return send_json(req, "{\"ok\":false,\"error\":\"invalid_credentials\"}", "401 Unauthorized");
    }

    char token[SESSION_TOKEN_LEN] = {0};
    if (!session_create(username, token)) {
        return send_json(req, "{\"ok\":false,\"error\":\"session_error\"}", "500 Internal Server Error");
    }

    s_login_attempts = 0;
    s_login_block_until = 0;

    cJSON *resp = cJSON_CreateObject();
    cJSON_AddBoolToObject(resp, "ok", true);
    cJSON_AddStringToObject(resp, "username", username);
    char *json_str = cJSON_PrintUnformatted(resp);
    cJSON_Delete(resp);

    char cookie[128];
    snprintf(cookie, sizeof(cookie), "session=%s; Path=/; SameSite=Lax", token);
    httpd_resp_set_hdr(req, "Set-Cookie", cookie);

    ESP_LOGI(TAG, "Login success");
    esp_err_t result = send_json(req, json_str, "200 OK");
    free(json_str);
    return result;
}

/* POST /api/logout */
static esp_err_t handle_api_logout(httpd_req_t *req)
{
    if (!is_same_origin(req, true)) {
        return send_json(req, "{\"ok\":false,\"error\":\"forbidden\"}", "403 Forbidden");
    }

    char token[SESSION_TOKEN_LEN] = {0};
    if (get_session_from_request(req, token, sizeof(token))) {
        session_destroy(token);
    }

    /* Clear cookie */
    httpd_resp_set_hdr(req, "Set-Cookie",
        "session=; Path=/; Max-Age=0; SameSite=Lax");

    return send_json(req, "{\"ok\":true}", "200 OK");
}

/* GET /api/wifi/scan - protected, returns JSON scan results */
static esp_err_t handle_api_wifi_scan(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", "401 Unauthorized");
    }

    wifi_scan_ctx_t ctx;
    ctx.sem = xSemaphoreCreateBinary();
    ctx.count = 0;
    if (!ctx.sem) {
        return send_json(req, "{\"ok\":false,\"error\":\"memory\"}", "500 Internal Server Error");
    }

    if (!wifi_manager_scan(&ctx, scan_complete_cb)) {
        vSemaphoreDelete(ctx.sem);
        return send_json(req, "{\"ok\":false,\"error\":\"scan_failed\"}", "200 OK");
    }

    if (xSemaphoreTake(ctx.sem, pdMS_TO_TICKS(5000)) != pdTRUE) {
        vSemaphoreDelete(ctx.sem);
        return send_json(req, "{\"ok\":false,\"error\":\"scan_timeout\"}", "200 OK");
    }
    vSemaphoreDelete(ctx.sem);

    cJSON *root = cJSON_CreateObject();
    cJSON_AddBoolToObject(root, "ok", true);
    cJSON *arr = cJSON_AddArrayToObject(root, "networks");
    for (int i = 0; i < ctx.count; i++) {
        cJSON *item = cJSON_CreateObject();
        cJSON_AddStringToObject(item, "ssid", ctx.entries[i].ssid);
        cJSON_AddNumberToObject(item, "rssi", ctx.entries[i].rssi);
        cJSON_AddStringToObject(item, "auth", ctx.entries[i].auth);
        cJSON_AddNumberToObject(item, "channel", ctx.entries[i].channel);
        cJSON_AddItemToArray(arr, item);
    }

    char *json_str = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, json_str, strlen(json_str));
    free(json_str);

    return ESP_OK;
}

/* POST /api/wifi/connect - protected, connect to given SSID */
static esp_err_t handle_api_wifi_connect(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", "401 Unauthorized");
    }

    if (!is_same_origin(req, true)) {
        return send_json(req, "{\"ok\":false,\"error\":\"forbidden\"}", "403 Forbidden");
    }

    char body[512] = {0};
    int ret = httpd_req_recv(req, body, sizeof(body) - 1);
    if (ret <= 0) {
        return send_json(req, "{\"ok\":false,\"error\":\"empty_body\"}", "200 OK");
    }
    body[ret] = '\0';

    char ssid[64] = {0};
    char password[64] = {0};
    wifi_sta_ip_config_t ip_cfg = {0};
    bool has_static_ip = false;

    cJSON *root = cJSON_Parse(body);
    if (root) {
        cJSON *s = cJSON_GetObjectItem(root, "ssid");
        cJSON *p = cJSON_GetObjectItem(root, "password");
        if (s && cJSON_IsString(s)) {
            strncpy(ssid, s->valuestring, sizeof(ssid) - 1);
        }
        if (p && cJSON_IsString(p)) {
            strncpy(password, p->valuestring, sizeof(password) - 1);
        }
        cJSON *ip_item = cJSON_GetObjectItem(root, "ip");
        if (ip_item && cJSON_IsString(ip_item) && ip_item->valuestring[0]) {
            strncpy(ip_cfg.ip, ip_item->valuestring, sizeof(ip_cfg.ip) - 1);
            has_static_ip = true;
            cJSON *gw = cJSON_GetObjectItem(root, "gateway");
            if (gw && cJSON_IsString(gw)) {
                strncpy(ip_cfg.gateway, gw->valuestring, sizeof(ip_cfg.gateway) - 1);
            }
            cJSON *nm = cJSON_GetObjectItem(root, "netmask");
            if (nm && cJSON_IsString(nm)) {
                strncpy(ip_cfg.netmask, nm->valuestring, sizeof(ip_cfg.netmask) - 1);
            }
            cJSON *dns = cJSON_GetObjectItem(root, "dns");
            if (dns && cJSON_IsString(dns)) {
                strncpy(ip_cfg.dns, dns->valuestring, sizeof(ip_cfg.dns) - 1);
            }
        }
        cJSON_Delete(root);
    }

    if (strlen(ssid) == 0) {
        return send_json(req, "{\"ok\":false,\"error\":\"missing_ssid\"}", "200 OK");
    }

    if (strlen(ssid) > 32) {
        return send_json(req, "{\"ok\":false,\"error\":\"ssid_too_long\"}", "400 Bad Request");
    }

    if (!is_valid_utf8_printable(ssid, sizeof(ssid))) {
        return send_json(req, "{\"ok\":false,\"error\":\"invalid_ssid\"}", "400 Bad Request");
    }

    if (strlen(password) > 64) {
        return send_json(req, "{\"ok\":false,\"error\":\"password_too_long\"}", "400 Bad Request");
    }

    if (password[0] && !is_valid_utf8_printable(password, sizeof(password))) {
        return send_json(req, "{\"ok\":false,\"error\":\"invalid_password\"}", "400 Bad Request");
    }

    if (has_static_ip && !ip_cfg.gateway[0]) {
        return send_json(req, "{\"ok\":false,\"error\":\"missing_gateway\"}", "400 Bad Request");
    }

    if (!wifi_manager_connect_sta(ssid, password, has_static_ip ? &ip_cfg : NULL)) {
        return send_json(req, "{\"ok\":false,\"error\":\"connect_error\"}", "200 OK");
    }

    vTaskDelay(pdMS_TO_TICKS(5000));

    cJSON *resp = cJSON_CreateObject();
    if (wifi_manager_is_sta_connected()) {
        cJSON_AddBoolToObject(resp, "ok", true);
        cJSON_AddStringToObject(resp, "ssid", wifi_manager_get_sta_ssid());
        cJSON_AddStringToObject(resp, "ip", wifi_manager_get_sta_ip());
    } else {
        cJSON_AddBoolToObject(resp, "ok", false);
        cJSON_AddStringToObject(resp, "error", "connection_failed");
        cJSON_AddStringToObject(resp, "ssid", ssid);
    }
    char *json_str = cJSON_PrintUnformatted(resp);
    cJSON_Delete(resp);
    esp_err_t result = send_json(req, json_str, "200 OK");
    free(json_str);
    return result;
}

/* POST /api/wifi/disconnect - protected, disconnect STA */
static esp_err_t handle_api_wifi_disconnect(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", "401 Unauthorized");
    }

    if (!is_same_origin(req, true)) {
        return send_json(req, "{\"ok\":false,\"error\":\"forbidden\"}", "403 Forbidden");
    }

    if (!wifi_manager_disconnect_sta()) {
        return send_json(req, "{\"ok\":false,\"error\":\"disconnect_failed\"}", "200 OK");
    }

    return send_json(req, "{\"ok\":true}", "200 OK");
}

/* GET /status - protected, serves full status page */
static esp_err_t handle_get_status(httpd_req_t *req)
{
    if (!require_auth(req)) {
        httpd_resp_set_status(req, "302 Found");
        httpd_resp_set_hdr(req, "Location", "/login");
        httpd_resp_send(req, NULL, 0);
        return ESP_OK;
    }
    return serve_static(req,
        _binary_status_html_start, _binary_status_html_end,
        "text/html; charset=utf-8");
}

/* GET /api/hardware/map - protected, return active/pending GPIO maps and safe options */
static esp_err_t handle_api_hardware_map_get(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", "401 Unauthorized");
    }

    return api_hardware_map_send(req);
}

/* POST /api/hardware/map - protected, save pending hardware map for reboot */
static esp_err_t handle_api_hardware_map_post(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", "401 Unauthorized");
    }

    if (!is_same_origin(req, false)) {
        return send_api_error(req, "forbidden", "Cross-origin hardware map save blocked",
                              "403 Forbidden");
    }

    char body[512] = {0};
    int ret = httpd_req_recv(req, body, sizeof(body) - 1);
    if (ret <= 0) {
        return send_api_error(req, "empty_body", "Request body is required", "400 Bad Request");
    }
    body[ret] = '\0';

    cJSON *root = cJSON_Parse(body);
    if (!root || !cJSON_IsObject(root)) {
        if (root) {
            cJSON_Delete(root);
        }
        return send_api_error(req, "invalid_json", "Expected a JSON object", "400 Bad Request");
    }

    hardware_map_t submitted = hardware_map_defaults();
    const char *error_code = NULL;
    const char *error_message = NULL;
    bool valid = api_hardware_parse_map_payload(root, &submitted, &error_code, &error_message);
    cJSON_Delete(root);
    if (!valid) {
        return send_api_error(req, error_code, error_message, "400 Bad Request");
    }

    hardware_map_t active = hardware_map_defaults();
    nvs_store_hardware_map_load_status_t active_status = nvs_store_load_hardware_map(&active);
    if (active_status == NVS_STORE_HARDWARE_MAP_DEFAULTS_ERROR) {
        return send_api_error(req, "hardware_map_load_failed",
                              "Could not load active hardware map",
                              "500 Internal Server Error");
    }

    bool saved = hardware_map_equal(&active, &submitted)
        ? nvs_store_clear_pending_hardware_map()
        : nvs_store_save_pending_hardware_map(&submitted);
    if (!saved) {
        return send_api_error(req, "pending_save_failed",
                              "Could not save pending hardware map",
                              "500 Internal Server Error");
    }

    return api_hardware_map_send(req);
}

/* GET /api/pump/config - protected, return persisted pump config plus read-only hardware defaults */
static esp_err_t handle_api_pump_config_get(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", "401 Unauthorized");
    }

    nvs_store_pump_settings_t settings;
    nvs_store_pump_settings_load_status_t status = nvs_store_load_pump_settings(&settings);
    if (status == NVS_STORE_PUMP_SETTINGS_DEFAULTS_ERROR) {
        return send_api_error(req, "settings_load_failed", "Could not load pump settings",
                              "500 Internal Server Error");
    }

    return api_pump_send_config(req, &settings, status, false);
}

/* POST /api/pump/config - protected, full replacement for editable pump settings */
static esp_err_t handle_api_pump_config_post(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", "401 Unauthorized");
    }

    if (!is_same_origin(req, false)) {
        return send_api_error(req, "forbidden", "Cross-origin pump config save blocked",
                              "403 Forbidden");
    }

    char body[512] = {0};
    int ret = httpd_req_recv(req, body, sizeof(body) - 1);
    if (ret <= 0) {
        return send_api_error(req, "empty_body", "Request body is required", "400 Bad Request");
    }
    body[ret] = '\0';

    cJSON *root = cJSON_Parse(body);
    if (!root || !cJSON_IsObject(root)) {
        if (root) {
            cJSON_Delete(root);
        }
        return send_api_error(req, "invalid_json", "Expected a JSON object", "400 Bad Request");
    }

    nvs_store_pump_settings_t settings;
    nvs_store_pump_settings_defaults(&settings);
    nvs_store_load_pump_settings(&settings);
    const char *error_code = NULL;
    const char *error_message = NULL;
    bool valid = api_pump_parse_settings_payload(root, &settings, &error_code, &error_message);
    cJSON_Delete(root);
    if (!valid) {
        return send_api_error(req, error_code, error_message, "400 Bad Request");
    }

    pump_control_status_t before_status = {0};
    bool had_status = pump_control_get_status(&before_status);
    bool was_running = had_status && before_status.running;

    if (!nvs_store_save_pump_settings(&settings)) {
        return send_api_error(req, "settings_save_failed", "Could not save pump settings",
                              "500 Internal Server Error");
    }

    pump_control_config_t config;
    api_pump_settings_to_runtime_config(&settings, &config);

    if (was_running) {
        pump_control_stop();
    }

    if (!pump_control_init(&config)) {
        pump_control_stop();
        return send_api_error(req, "runtime_apply_failed",
                              "Saved settings but could not apply pump runtime config",
                              "500 Internal Server Error");
    }

    if (was_running && !pump_control_start()) {
        pump_control_stop();
        return send_api_error(req, "restart_failed",
                              "Saved settings but could not restart pump control",
                              "500 Internal Server Error");
    }

    return api_pump_send_config(req, &settings, NVS_STORE_PUMP_SETTINGS_LOADED, true);
}

/* GET /api/pump/status - protected, return machine-friendly pump runtime status */
static esp_err_t handle_api_pump_status(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", "401 Unauthorized");
    }

    cJSON *root = cJSON_CreateObject();
    if (!root) {
        return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
    }

    cJSON_AddBoolToObject(root, "ok", true);
    if (!api_pump_add_status_fields(root)) {
        cJSON_Delete(root);
        return send_api_error(req, "status_unavailable", "Pump status is unavailable",
                              "409 Conflict");
    }

    char *json_str = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    if (!json_str) {
        return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
    }

    esp_err_t result = send_json(req, json_str, "200 OK");
    free(json_str);
    return result;
}

/* GET /api/cooling/status - protected, return machine-friendly cooling runtime status */
static esp_err_t handle_api_cooling_status(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", "401 Unauthorized");
    }

    cJSON *root = cJSON_CreateObject();
    if (!root) {
        return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
    }

    cJSON_AddBoolToObject(root, "ok", true);
    if (!api_cooling_add_status_fields(root)) {
        cJSON_Delete(root);
        return send_api_error(req, "status_unavailable", "Cooling status is unavailable",
                              "409 Conflict");
    }

    char *json_str = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    if (!json_str) {
        return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
    }

    esp_err_t result = send_json(req, json_str, "200 OK");
    free(json_str);
    return result;
}

/* GET /api/cooling/config - protected, return persisted cooling config plus status */
static esp_err_t handle_api_cooling_config_get(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", "401 Unauthorized");
    }

    nvs_store_cooling_settings_t settings;
    nvs_store_cooling_settings_load_status_t status = nvs_store_load_cooling_settings(&settings);
    if (status == NVS_STORE_COOLING_SETTINGS_DEFAULTS_ERROR ||
        status == NVS_STORE_COOLING_SETTINGS_DEFAULTS_INVALID) {
        return send_api_error(req, "settings_load_failed",
                              "Could not load cooling settings",
                              "500 Internal Server Error");
    }

    return api_cooling_send_config(req, &settings, status, true);
}

/* POST /api/cooling/config - protected, save and apply cooling config */
static esp_err_t handle_api_cooling_config_post(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", "401 Unauthorized");
    }

    if (!is_same_origin(req, false)) {
        return send_api_error(req, "forbidden", "Cross-origin cooling config save blocked",
                              "403 Forbidden");
    }

    char body[512] = {0};
    int ret = httpd_req_recv(req, body, sizeof(body) - 1);
    if (ret <= 0) {
        return send_api_error(req, "empty_body", "Request body is required", "400 Bad Request");
    }
    body[ret] = '\0';

    cJSON *root = cJSON_Parse(body);
    if (!root || !cJSON_IsObject(root)) {
        if (root) {
            cJSON_Delete(root);
        }
        return send_api_error(req, "invalid_json", "Expected a JSON object", "400 Bad Request");
    }

    nvs_store_cooling_settings_t settings;
    nvs_store_cooling_settings_defaults(&settings);
    nvs_store_load_cooling_settings(&settings);
    const char *error_code = NULL;
    const char *error_message = NULL;
    bool valid = api_cooling_parse_config_payload(root, &settings, &error_code, &error_message);
    cJSON_Delete(root);
    if (!valid) {
        return send_api_error(req, error_code, error_message, "400 Bad Request");
    }

    if (!nvs_store_save_cooling_settings(&settings)) {
        return send_api_error(req, "settings_save_failed", "Could not save cooling settings",
                              "500 Internal Server Error");
    }

    cooling_control_config_t config;
    api_cooling_settings_to_runtime_config(&settings, &config);
    if (!cooling_control_init(&config)) {
        cooling_control_stop();
        return api_cooling_send_apply_error(req, "runtime_apply_failed",
                                            "Saved settings but could not apply cooling runtime config",
                                            &settings);
    }

    return api_cooling_send_config(req, &settings, NVS_STORE_COOLING_SETTINGS_LOADED, true);
}

/* POST /api/cooling/mode - protected, change runtime cooling mode */
static esp_err_t handle_api_cooling_mode_post(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", "401 Unauthorized");
    }

    if (!is_same_origin(req, false)) {
        return send_api_error(req, "forbidden", "Cross-origin cooling mode change blocked",
                              "403 Forbidden");
    }

    char body[128] = {0};
    int ret = httpd_req_recv(req, body, sizeof(body) - 1);
    if (ret <= 0) {
        return send_api_error(req, "empty_body", "Request body is required", "400 Bad Request");
    }
    body[ret] = '\0';

    cJSON *root = cJSON_Parse(body);
    if (!root || !cJSON_IsObject(root)) {
        if (root) {
            cJSON_Delete(root);
        }
        return send_api_error(req, "invalid_json", "Expected a JSON object", "400 Bad Request");
    }

    hardware_cooling_mode_t mode = HARDWARE_COOLING_MODE_FORCE_OFF;
    const cJSON *mode_item = cJSON_GetObjectItem(root, "mode");
    bool mode_present = mode_item != NULL;
    bool valid = api_cooling_parse_mode(mode_item, &mode);
    cJSON_Delete(root);
    if (!valid) {
        return send_api_error(req, mode_present ? "invalid_cooling_mode" : "missing_field",
                              "mode", "400 Bad Request");
    }

    bool mode_ok = false;
    if (mode == HARDWARE_COOLING_MODE_TEST_ON) {
        mode_ok = cooling_control_start_test();
    } else {
        mode_ok = cooling_control_set_mode(api_cooling_mode_from_hardware(mode));
        if (mode_ok) {
            nvs_store_cooling_settings_t settings;
            nvs_store_cooling_settings_defaults(&settings);
            nvs_store_load_cooling_settings(&settings);
            settings.mode = mode;
            if (!nvs_store_save_cooling_settings(&settings)) {
                return send_api_error(req, "settings_save_failed",
                                      "Cooling mode changed but could not be saved",
                                      "500 Internal Server Error");
            }
        }
    }
    if (!mode_ok) {
        return send_api_error(req, "mode_change_failed",
                              "Cooling mode could not be changed",
                              "409 Conflict");
    }

    nvs_store_cooling_settings_t settings;
    nvs_store_cooling_settings_defaults(&settings);
    nvs_store_cooling_settings_load_status_t status = nvs_store_load_cooling_settings(&settings);
    return api_cooling_send_config(req, &settings, status, true);
}

/* POST /api/pump/start - protected, idempotently start pump control */
static esp_err_t handle_api_pump_start(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", "401 Unauthorized");
    }

    if (!is_same_origin(req, false)) {
        return send_api_error(req, "forbidden", "Cross-origin pump start blocked", "403 Forbidden");
    }

    pump_control_status_t before_status = {0};
    if (!pump_control_get_status(&before_status)) {
        return send_api_error(req, "status_unavailable", "Pump status is unavailable",
                              "409 Conflict");
    }

    bool already_running = before_status.running;
    if (!already_running && !pump_control_start()) {
        pump_control_stop();
        return send_api_error_with_pump_status(req, "start_failed",
                                               "Pump control could not be started",
                                               "500 Internal Server Error");
    }

    cJSON *root = cJSON_CreateObject();
    if (!root) {
        return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
    }

    cJSON_AddBoolToObject(root, "ok", true);
    cJSON_AddBoolToObject(root, "already_running", already_running);
    if (!api_pump_add_status_object(root)) {
        cJSON_Delete(root);
        return send_api_error(req, "status_unavailable", "Pump status is unavailable",
                              "409 Conflict");
    }

    char *json_str = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    if (!json_str) {
        return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
    }

    esp_err_t result = send_json(req, json_str, "200 OK");
    free(json_str);
    return result;
}

/* POST /api/pump/stop - protected, idempotently stop pump control */
static esp_err_t handle_api_pump_stop(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", "401 Unauthorized");
    }

    if (!is_same_origin(req, false)) {
        return send_api_error(req, "forbidden", "Cross-origin pump stop blocked", "403 Forbidden");
    }

    pump_control_status_t before_status = {0};
    if (!pump_control_get_status(&before_status)) {
        return send_api_error(req, "status_unavailable", "Pump status is unavailable",
                              "409 Conflict");
    }

    bool already_stopped = !before_status.running;
    if (!already_stopped || before_status.relay_energized) {
        if (!pump_control_stop()) {
            return send_api_error_with_pump_status(req, "stop_failed",
                                                   "Pump control could not be stopped",
                                                   "500 Internal Server Error");
        }
    }

    pump_control_status_t after_status = {0};
    if (!pump_control_get_status(&after_status) ||
        after_status.running || after_status.relay_energized) {
        return send_api_error_with_pump_status(req, "stop_failed",
                                               "Pump relay inactive state could not be confirmed",
                                               "409 Conflict");
    }

    cJSON *root = cJSON_CreateObject();
    if (!root) {
        return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
    }

    cJSON_AddBoolToObject(root, "ok", true);
    cJSON_AddBoolToObject(root, "already_stopped", already_stopped);
    if (!api_pump_add_status_object(root)) {
        cJSON_Delete(root);
        return send_api_error(req, "status_unavailable", "Pump status is unavailable",
                              "409 Conflict");
    }

    char *json_str = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    if (!json_str) {
        return send_api_error(req, "memory", "JSON allocation failed", "500 Internal Server Error");
    }

    esp_err_t result = send_json(req, json_str, "200 OK");
    free(json_str);
    return result;
}

/* GET /api/status - protected, return device status JSON */
static esp_err_t handle_api_status(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", "401 Unauthorized");
    }

    bool sta_conn = wifi_manager_is_sta_connected();
    bool ap_up = wifi_manager_is_ap_enabled();

    cJSON *root = cJSON_CreateObject();
    cJSON_AddBoolToObject(root, "ok", true);

    /* ---------- System ---------- */
    esp_chip_info_t chip;
    esp_chip_info(&chip);
    cJSON_AddStringToObject(root, "chip_model", chip_model_to_string(chip.model));
    cJSON_AddNumberToObject(root, "chip_revision", chip.revision);
    cJSON_AddNumberToObject(root, "chip_cores", chip.cores);
    cJSON_AddNumberToObject(root, "cpu_freq_mhz", CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ);
    cJSON_AddStringToObject(root, "idf_version", esp_get_idf_version());
    cJSON_AddStringToObject(root, "project_name", APP_TEMPLATE_NAME);
    cJSON_AddStringToObject(root, "project_version", APP_TEMPLATE_FIRMWARE_VERSION);

    /* ---------- MAC addresses ---------- */
    uint8_t mac[6];
    char mac_str[18];
    esp_read_mac(mac, ESP_MAC_WIFI_STA);
    format_mac(mac, mac_str);
    cJSON_AddStringToObject(root, "mac_sta", mac_str);
    esp_read_mac(mac, ESP_MAC_WIFI_SOFTAP);
    format_mac(mac, mac_str);
    cJSON_AddStringToObject(root, "mac_ap", mac_str);

    /* ---------- Memory ---------- */
    uint32_t free_heap = wifi_manager_get_free_heap();
    uint32_t min_free_heap = esp_get_minimum_free_heap_size();
    uint32_t total_heap = heap_caps_get_total_size(MALLOC_CAP_INTERNAL);
    cJSON_AddNumberToObject(root, "free_heap", (double)free_heap);
    cJSON_AddNumberToObject(root, "min_free_heap", (double)min_free_heap);
    cJSON_AddNumberToObject(root, "total_heap", (double)total_heap);

    /* ---------- Uptime ---------- */
    cJSON_AddNumberToObject(root, "uptime_ms", (double)wifi_manager_get_uptime_ms());

    /* ---------- Wi-Fi ---------- */
    wifi_mode_t wmode;
    esp_wifi_get_mode(&wmode);
    const char *wmode_str = "NULL";
    if (wmode == WIFI_MODE_STA)      wmode_str = "STA";
    else if (wmode == WIFI_MODE_AP)  wmode_str = "AP";
    else if (wmode == WIFI_MODE_APSTA) wmode_str = "APSTA";
    cJSON_AddStringToObject(root, "wifi_mode", wmode_str);

    /* AP info */
    cJSON_AddBoolToObject(root, "ap_enabled", ap_up);
    cJSON_AddStringToObject(root, "ap_ssid", ap_up ? AP_SSID : "");
    cJSON_AddStringToObject(root, "ap_ip", ap_up ? wifi_manager_get_ap_ip() : "");

    wifi_sta_list_t sta_list;
    if (ap_up && esp_wifi_ap_get_sta_list(&sta_list) == ESP_OK) {
        cJSON_AddNumberToObject(root, "ap_clients", sta_list.num);
    } else {
        cJSON_AddNumberToObject(root, "ap_clients", 0);
    }

    /* STA info */
    cJSON_AddBoolToObject(root, "sta_connected", sta_conn);
    cJSON_AddStringToObject(root, "sta_ip", sta_conn ? wifi_manager_get_sta_ip() : "");
    cJSON_AddStringToObject(root, "sta_ssid", sta_conn ? wifi_manager_get_sta_ssid() : "");

    if (sta_conn) {
        wifi_ap_record_t ap_rec;
        if (esp_wifi_sta_get_ap_info(&ap_rec) == ESP_OK) {
            cJSON_AddNumberToObject(root, "sta_rssi", ap_rec.rssi);
            cJSON_AddNumberToObject(root, "sta_channel", ap_rec.primary);
            cJSON_AddStringToObject(root, "sta_auth", wifi_auth_mode_to_string(ap_rec.authmode));
        }
    }

    /* ---------- Services ---------- */
    cJSON_AddBoolToObject(root, "dns_server", dns_server_is_running());

    char *json_str = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    esp_err_t result = send_json(req, json_str, "200 OK");
    free(json_str);
    return result;
}

/* --------------- Server Start --------------- */

bool web_server_start(void)
{
    httpd_handle_t server = NULL;
    httpd_config_t config = HTTPD_DEFAULT_CONFIG();
    config.max_uri_handlers = APP_TEMPLATE_HTTP_MAX_URI_HANDLERS;
    config.lru_purge_enable = true;

    if (httpd_start(&server, &config) != ESP_OK) {
        ESP_LOGE(TAG, "Failed to start HTTP server");
        return false;
    }

    const httpd_uri_t routes[] = {
        { .uri = "/",              .method = HTTP_GET,  .handler = handle_root,           .user_ctx = NULL },
        { .uri = "/login",         .method = HTTP_GET,  .handler = handle_get_login,      .user_ctx = NULL },
        { .uri = "/dashboard",     .method = HTTP_GET,  .handler = handle_get_dashboard,  .user_ctx = NULL },
        { .uri = "/status",        .method = HTTP_GET,  .handler = handle_get_status,     .user_ctx = NULL },
        { .uri = "/wifi",          .method = HTTP_GET,  .handler = handle_get_wifi,       .user_ctx = NULL },
        { .uri = "/style.css",     .method = HTTP_GET,  .handler = handle_style_css,      .user_ctx = NULL },
        { .uri = "/app.js",        .method = HTTP_GET,  .handler = handle_app_js,         .user_ctx = NULL },
        { .uri = "/api/login",     .method = HTTP_POST, .handler = handle_api_login,      .user_ctx = NULL },
        { .uri = "/api/logout",    .method = HTTP_POST, .handler = handle_api_logout,     .user_ctx = NULL },
        { .uri = "/api/wifi/scan", .method = HTTP_GET,  .handler = handle_api_wifi_scan,  .user_ctx = NULL },
        { .uri = "/api/wifi/connect", .method = HTTP_POST, .handler = handle_api_wifi_connect, .user_ctx = NULL },
        { .uri = "/api/wifi/disconnect", .method = HTTP_POST, .handler = handle_api_wifi_disconnect, .user_ctx = NULL },
        { .uri = "/api/status",    .method = HTTP_GET,  .handler = handle_api_status,     .user_ctx = NULL },
        { .uri = "/api/hardware/map", .method = HTTP_GET, .handler = handle_api_hardware_map_get, .user_ctx = NULL },
        { .uri = "/api/hardware/map", .method = HTTP_POST, .handler = handle_api_hardware_map_post, .user_ctx = NULL },
        { .uri = "/api/pump/config", .method = HTTP_GET,  .handler = handle_api_pump_config_get, .user_ctx = NULL },
        { .uri = "/api/pump/config", .method = HTTP_POST, .handler = handle_api_pump_config_post, .user_ctx = NULL },
        { .uri = "/api/pump/status", .method = HTTP_GET,  .handler = handle_api_pump_status, .user_ctx = NULL },
        { .uri = "/api/cooling/status", .method = HTTP_GET, .handler = handle_api_cooling_status, .user_ctx = NULL },
        { .uri = "/api/cooling/config", .method = HTTP_GET, .handler = handle_api_cooling_config_get, .user_ctx = NULL },
        { .uri = "/api/cooling/config", .method = HTTP_POST, .handler = handle_api_cooling_config_post, .user_ctx = NULL },
        { .uri = "/api/cooling/mode", .method = HTTP_POST, .handler = handle_api_cooling_mode_post, .user_ctx = NULL },
        { .uri = "/api/pump/start",  .method = HTTP_POST, .handler = handle_api_pump_start,  .user_ctx = NULL },
        { .uri = "/api/pump/stop",   .method = HTTP_POST, .handler = handle_api_pump_stop,   .user_ctx = NULL },
    };

    for (int i = 0; i < sizeof(routes) / sizeof(routes[0]); i++) {
        esp_err_t err = httpd_register_uri_handler(server, &routes[i]);
        if (err != ESP_OK) {
            ESP_LOGE(TAG, "Failed to register route %s: %d", routes[i].uri, err);
        }
    }

    ESP_LOGI(TAG, "HTTP server started on port %d", config.server_port);
    return true;
}
