#include "web_server.h"
#include "session.h"
#include "wifi_manager.h"
#include "esp_http_server.h"
#include "esp_wifi.h"
#include "esp_log.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

static const char *TAG = "web_server";

/* Embedded file declarations generated by EMBED_FILES in CMakeLists.txt */
extern const uint8_t _binary_login_html_start[] asm("_binary_login_html_start");
extern const uint8_t _binary_login_html_end[]   asm("_binary_login_html_end");
extern const uint8_t _binary_dashboard_html_start[] asm("_binary_dashboard_html_start");
extern const uint8_t _binary_dashboard_html_end[]   asm("_binary_dashboard_html_end");
extern const uint8_t _binary_wifi_html_start[] asm("_binary_wifi_html_start");
extern const uint8_t _binary_wifi_html_end[]   asm("_binary_wifi_html_end");
extern const uint8_t _binary_style_css_start[] asm("_binary_style_css_start");
extern const uint8_t _binary_style_css_end[]   asm("_binary_style_css_end");
extern const uint8_t _binary_app_js_start[] asm("_binary_app_js_start");
extern const uint8_t _binary_app_js_end[]   asm("_binary_app_js_end");

/*
 * WARNING: Default credentials are admin/admin123.
 * These MUST be changed before any production deployment.
 * This is a local-prototype login system, not internet-facing security.
 */
#define DEFAULT_USERNAME "admin"
#define DEFAULT_PASSWORD "admin123"

/* --------------- Helpers --------------- */

/* Extract session token from Cookie header.
   WARNING: This is a local-prototype auth scheme.
   Session tokens are random but transmitted as plain cookies.
   Not secure against network sniffing on open Wi-Fi. */
static bool get_session_from_request(httpd_req_t *req, char *token_out, size_t token_len)
{
    size_t buf_len = httpd_req_get_hdr_value_len(req, "Cookie");
    if (buf_len <= 0) return false;

    char *cookie_buf = malloc(buf_len + 1);
    if (!cookie_buf) return false;

    if (httpd_req_get_hdr_value_str(req, "Cookie", cookie_buf, buf_len + 1) != ESP_OK) {
        free(cookie_buf);
        return false;
    }

    /* Simple parse: find "session=" */
    const char *start = strstr(cookie_buf, "session=");
    if (start) {
        start += 8; /* skip "session=" */
        const char *end = strchr(start, ';');
        size_t len = end ? (size_t)(end - start) : strlen(start);
        if (len >= token_len) len = token_len - 1;
        memcpy(token_out, start, len);
        token_out[len] = '\0';
        free(cookie_buf);
        return true;
    }
    free(cookie_buf);
    return false;
}

/* Auth check middleware - returns true if session is valid */
static bool require_auth(httpd_req_t *req)
{
    char token[SESSION_TOKEN_LEN] = {0};
    if (!get_session_from_request(req, token, sizeof(token))) return false;
    return session_validate(token);
}

/* Send JSON response */
static esp_err_t send_json(httpd_req_t *req, const char *json, int status_code)
{
    httpd_resp_set_type(req, "application/json");
    httpd_resp_set_status(req, status_code == 200 ? "200 OK" : "401 Unauthorized");
    httpd_resp_send(req, json, strlen(json));
    return ESP_OK;
}

/* Send a static embedded file */
static esp_err_t serve_static(httpd_req_t *req, const uint8_t *start, const uint8_t *end,
                              const char *mime_type)
{
    size_t len = (size_t)(end - start);
    httpd_resp_set_type(req, mime_type);
    httpd_resp_send(req, (const char *)start, len);
    return ESP_OK;
}

/* --------------- Route Handlers --------------- */

/* GET / - redirect based on auth status */
static esp_err_t handle_root(httpd_req_t *req)
{
    char token[SESSION_TOKEN_LEN] = {0};
    if (get_session_from_request(req, token, sizeof(token)) && session_validate(token)) {
        httpd_resp_set_status(req, "302 Found");
        httpd_resp_set_hdr(req, "Location", "/dashboard");
        httpd_resp_send(req, NULL, 0);
    } else {
        httpd_resp_set_status(req, "302 Found");
        httpd_resp_set_hdr(req, "Location", "/login");
        httpd_resp_send(req, NULL, 0);
    }
    return ESP_OK;
}

/* GET /login */
static esp_err_t handle_get_login(httpd_req_t *req)
{
    return serve_static(req,
        _binary_login_html_start, _binary_login_html_end,
        "text/html; charset=utf-8");
}

/* GET /dashboard - protected */
static esp_err_t handle_get_dashboard(httpd_req_t *req)
{
    if (!require_auth(req)) {
        httpd_resp_set_status(req, "302 Found");
        httpd_resp_set_hdr(req, "Location", "/login");
        httpd_resp_send(req, NULL, 0);
        return ESP_OK;
    }
    return serve_static(req,
        _binary_dashboard_html_start, _binary_dashboard_html_end,
        "text/html; charset=utf-8");
}

/* GET /wifi - protected */
static esp_err_t handle_get_wifi(httpd_req_t *req)
{
    if (!require_auth(req)) {
        httpd_resp_set_status(req, "302 Found");
        httpd_resp_set_hdr(req, "Location", "/login");
        httpd_resp_send(req, NULL, 0);
        return ESP_OK;
    }
    return serve_static(req,
        _binary_wifi_html_start, _binary_wifi_html_end,
        "text/html; charset=utf-8");
}

/* GET /style.css */
static esp_err_t handle_style_css(httpd_req_t *req)
{
    return serve_static(req,
        _binary_style_css_start, _binary_style_css_end,
        "text/css; charset=utf-8");
}

/* GET /app.js */
static esp_err_t handle_app_js(httpd_req_t *req)
{
    return serve_static(req,
        _binary_app_js_start, _binary_app_js_end,
        "application/javascript; charset=utf-8");
}

/* POST /api/login */
static esp_err_t handle_api_login(httpd_req_t *req)
{
    /* Read body */
    char body[256] = {0};
    int ret = httpd_req_recv(req, body, sizeof(body) - 1);
    if (ret <= 0) {
        return send_json(req, "{\"ok\":false,\"error\":\"empty_body\"}", 401);
    }
    body[ret] = '\0';

    /* Simple form-data or JSON parsing */
    char username[64] = {0};
    char password[64] = {0};

    /* Try JSON format: {"ssid":"...", "password":"..."} but for login it's form-urlencoded from HTML form */
    /* Login page submits as: username=XXX&password=YYY (form-urlencoded) */
    /* Also handle JSON for API clients */
    const char *user_start = strstr(body, "username=");
    if (user_start) {
        /* Form-urlencoded */
        user_start += 9;
        const char *user_end = strchr(user_start, '&');
        size_t len = user_end ? (size_t)(user_end - user_start) : strlen(user_start);
        if (len > 63) len = 63;
        memcpy(username, user_start, len);

        const char *pass_start = strstr(body, "password=");
        if (pass_start) {
            pass_start += 9;
            const char *pass_end = strchr(pass_start, '&');
            len = pass_end ? (size_t)(pass_end - pass_start) : strlen(pass_start);
            if (len > 63) len = 63;
            memcpy(password, pass_start, len);
        }
    } else {
        /* Try JSON */
        const char *u = strstr(body, "\"username\"");
        const char *p = strstr(body, "\"password\"");
        if (u) {
            u = strchr(u, ':');
            if (u) {
                u = strchr(u, '"');
                if (u) { u++; const char *ue = strchr(u, '"');
                    if (ue) { size_t len = ue - u; if (len > 63) len = 63;
                        memcpy(username, u, len); }
                }
            }
        }
        if (p) {
            p = strchr(p, ':');
            if (p) {
                p = strchr(p, '"');
                if (p) { p++; const char *pe = strchr(p, '"');
                    if (pe) { size_t len = pe - p; if (len > 63) len = 63;
                        memcpy(password, p, len); }
                }
            }
        }
    }

    /* URL-decode basic: replace + with space, decode %XX */
    /* (simplified - not handling full URL decode for prototype) */

    if (strlen(username) == 0 || strlen(password) == 0) {
        return send_json(req, "{\"ok\":false,\"error\":\"missing_fields\"}", 401);
    }

    /* Validate credentials */
    if (strcmp(username, DEFAULT_USERNAME) != 0 || strcmp(password, DEFAULT_PASSWORD) != 0) {
        ESP_LOGW(TAG, "Login failed for user: %s", username);
        return send_json(req, "{\"ok\":false,\"error\":\"invalid_credentials\"}", 401);
    }

    /* Create session */
    char token[SESSION_TOKEN_LEN] = {0};
    if (!session_create(username, token)) {
        return send_json(req, "{\"ok\":false,\"error\":\"session_error\"}", 401);
    }

    /* Build JSON response */
    char json[256];
    snprintf(json, sizeof(json),
        "{\"ok\":true,\"token\":\"%s\",\"username\":\"%s\"}", token, username);

    /* Set session cookie.
       WARNING: Non-HttpOnly for local prototype JS access.
       NOT suitable for internet-facing production. */
    char cookie[128];
    snprintf(cookie, sizeof(cookie),
        "session=%s; Path=/", token);
    httpd_resp_set_hdr(req, "Set-Cookie", cookie);

    ESP_LOGI(TAG, "Login success for: %s", username);
    return send_json(req, json, 200);
}

/* POST /api/logout */
static esp_err_t handle_api_logout(httpd_req_t *req)
{
    char token[SESSION_TOKEN_LEN] = {0};
    if (get_session_from_request(req, token, sizeof(token))) {
        session_destroy(token);
    }

    /* Clear cookie */
    httpd_resp_set_hdr(req, "Set-Cookie",
        "session=; Path=/; Max-Age=0");

    return send_json(req, "{\"ok\":true}", 200);
}

/* GET /api/wifi/scan - protected, returns JSON scan results */
static esp_err_t handle_api_wifi_scan(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", 401);
    }

    /* Run scan in blocking mode */
    uint16_t num_aps = 0;
    wifi_scan_config_t scan_cfg = {
        .ssid = NULL,
        .bssid = NULL,
        .channel = 0,
        .show_hidden = false,
        .scan_type = WIFI_SCAN_TYPE_ACTIVE,
        .scan_time.active.min = 100,
        .scan_time.active.max = 300,
    };

    esp_err_t scan_ret = esp_wifi_scan_start(&scan_cfg, true); /* blocking */
    if (scan_ret != ESP_OK) {
        return send_json(req, "{\"ok\":false,\"error\":\"scan_failed\"}", 200);
    }

    esp_wifi_scan_get_ap_num(&num_aps);
    if (num_aps > WIFI_SCAN_MAX) num_aps = WIFI_SCAN_MAX;

    wifi_ap_record_t *ap_info = calloc(num_aps, sizeof(wifi_ap_record_t));
    if (ap_info) {
        esp_wifi_scan_get_ap_records(&num_aps, ap_info);

        /* Build JSON array */
        char *json = malloc(4096);
        if (!json) {
            free(ap_info);
            return send_json(req, "{\"ok\":false,\"error\":\"memory\"}", 200);
        }

        int offset = snprintf(json, 4096, "{\"ok\":true,\"networks\":[");
        for (int i = 0; i < num_aps; i++) {
            const char *auth_str = "Unknown";
            switch (ap_info[i].authmode) {
            case WIFI_AUTH_OPEN:          auth_str = "Open"; break;
            case WIFI_AUTH_WEP:           auth_str = "WEP"; break;
            case WIFI_AUTH_WPA_PSK:       auth_str = "WPA"; break;
            case WIFI_AUTH_WPA2_PSK:      auth_str = "WPA2"; break;
            case WIFI_AUTH_WPA_WPA2_PSK:  auth_str = "WPA/WPA2"; break;
            case WIFI_AUTH_WPA3_PSK:      auth_str = "WPA3"; break;
            case WIFI_AUTH_WPA2_WPA3_PSK: auth_str = "WPA2/WPA3"; break;
            default: break;
            }
            offset += snprintf(json + offset, 4096 - offset,
                "%s{\"ssid\":\"%s\",\"rssi\":%d,\"auth\":\"%s\",\"channel\":%d}",
                (i > 0 ? "," : ""),
                ap_info[i].ssid, ap_info[i].rssi, auth_str, ap_info[i].primary);
        }
        snprintf(json + offset, 4096 - offset, "]}");

        free(ap_info);
        httpd_resp_set_type(req, "application/json");
        httpd_resp_send(req, json, strlen(json));
        free(json);
    } else {
        return send_json(req, "{\"ok\":false,\"error\":\"memory\"}", 200);
    }

    return ESP_OK;
}

/* POST /api/wifi/connect - protected, connect to given SSID */
static esp_err_t handle_api_wifi_connect(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", 401);
    }

    char body[512] = {0};
    int ret = httpd_req_recv(req, body, sizeof(body) - 1);
    if (ret <= 0) {
        return send_json(req, "{\"ok\":false,\"error\":\"empty_body\"}", 200);
    }
    body[ret] = '\0';

    /* Parse JSON: {"ssid":"...","password":"..."} */
    char ssid[64] = {0};
    char password[64] = {0};

    const char *s = strstr(body, "\"ssid\"");
    if (s) {
        s = strchr(s, ':');
        if (s) {
            s = strchr(s, '"');
            if (s) { s++;
                const char *se = strchr(s, '"');
                if (se) {
                    size_t len = (size_t)(se - s);
                    if (len > 63) len = 63;
                    memcpy(ssid, s, len);
                }
            }
        }
    }

    const char *p = strstr(body, "\"password\"");
    if (p) {
        p = strchr(p, ':');
        if (p) {
            p = strchr(p, '"');
            if (p) { p++;
                const char *pe = strchr(p, '"');
                if (pe) {
                    size_t len = (size_t)(pe - p);
                    if (len > 63) len = 63;
                    memcpy(password, p, len);
                }
            }
        }
    }

    if (strlen(ssid) == 0) {
        return send_json(req, "{\"ok\":false,\"error\":\"missing_ssid\"}", 200);
    }

    /* Attempt connection */
    wifi_manager_connect_sta(ssid, password);

    /* Wait briefly for connection result */
    vTaskDelay(pdMS_TO_TICKS(5000));

    char json[256];
    if (wifi_manager_is_sta_connected()) {
        snprintf(json, sizeof(json),
            "{\"ok\":true,\"ssid\":\"%s\",\"ip\":\"%s\"}",
            wifi_manager_get_sta_ssid(), wifi_manager_get_sta_ip());
    } else {
        snprintf(json, sizeof(json),
            "{\"ok\":false,\"error\":\"connection_failed\",\"ssid\":\"%s\"}", ssid);
    }

    return send_json(req, json, 200);
}

/* GET /api/status - protected, return device status JSON */
static esp_err_t handle_api_status(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", 401);
    }

    char json[512];
    snprintf(json, sizeof(json),
        "{"
        "\"ok\":true,"
        "\"ap_enabled\":%s,"
        "\"ap_ip\":\"%s\","
        "\"sta_connected\":%s,"
        "\"sta_ip\":\"%s\","
        "\"sta_ssid\":\"%s\","
        "\"uptime_ms\":%lld,"
        "\"free_heap\":%lu"
        "}",
        wifi_manager_is_ap_enabled() ? "true" : "false",
        wifi_manager_is_ap_enabled() ? wifi_manager_get_ap_ip() : "",
        wifi_manager_is_sta_connected() ? "true" : "false",
        wifi_manager_is_sta_connected() ? wifi_manager_get_sta_ip() : "",
        wifi_manager_is_sta_connected() ? wifi_manager_get_sta_ssid() : "",
        wifi_manager_get_uptime_ms(),
        (unsigned long)wifi_manager_get_free_heap());

    return send_json(req, json, 200);
}

/* --------------- Server Start --------------- */

bool web_server_start(void)
{
    httpd_handle_t server = NULL;
    httpd_config_t config = HTTPD_DEFAULT_CONFIG();
    config.max_uri_handlers = 16;
    config.lru_purge_enable = true;

    if (httpd_start(&server, &config) != ESP_OK) {
        ESP_LOGE(TAG, "Failed to start HTTP server");
        return false;
    }

    const httpd_uri_t routes[] = {
        { .uri = "/",              .method = HTTP_GET,  .handler = handle_root,           .user_ctx = NULL },
        { .uri = "/login",         .method = HTTP_GET,  .handler = handle_get_login,      .user_ctx = NULL },
        { .uri = "/dashboard",     .method = HTTP_GET,  .handler = handle_get_dashboard,  .user_ctx = NULL },
        { .uri = "/wifi",          .method = HTTP_GET,  .handler = handle_get_wifi,       .user_ctx = NULL },
        { .uri = "/style.css",     .method = HTTP_GET,  .handler = handle_style_css,      .user_ctx = NULL },
        { .uri = "/app.js",        .method = HTTP_GET,  .handler = handle_app_js,         .user_ctx = NULL },
        { .uri = "/api/login",     .method = HTTP_POST, .handler = handle_api_login,      .user_ctx = NULL },
        { .uri = "/api/logout",    .method = HTTP_POST, .handler = handle_api_logout,     .user_ctx = NULL },
        { .uri = "/api/wifi/scan", .method = HTTP_GET,  .handler = handle_api_wifi_scan,  .user_ctx = NULL },
        { .uri = "/api/wifi/connect", .method = HTTP_POST, .handler = handle_api_wifi_connect, .user_ctx = NULL },
        { .uri = "/api/status",    .method = HTTP_GET,  .handler = handle_api_status,     .user_ctx = NULL },
    };

    for (int i = 0; i < sizeof(routes) / sizeof(routes[0]); i++) {
        httpd_register_uri_handler(server, &routes[i]);
    }

    ESP_LOGI(TAG, "HTTP server started on port %d", config.server_port);
    return true;
}
