#include "web_server.h"
#include "session.h"
#include "wifi_manager.h"
#include "esp_http_server.h"
#include "esp_wifi.h"
#include "esp_log.h"
#include "cJSON.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"

static const char *TAG = "web_server";

/* Embedded file declarations generated by EMBED_FILES in CMakeLists.txt */
extern const uint8_t _binary_login_html_start[] asm("_binary_login_html_start");
extern const uint8_t _binary_login_html_end[]   asm("_binary_login_html_end");
extern const uint8_t _binary_dashboard_html_start[] asm("_binary_dashboard_html_start");
extern const uint8_t _binary_dashboard_html_end[]   asm("_binary_dashboard_html_end");
extern const uint8_t _binary_wifi_html_start[] asm("_binary_wifi_html_start");
extern const uint8_t _binary_wifi_html_end[]   asm("_binary_wifi_html_end");
extern const uint8_t _binary_style_css_start[] asm("_binary_style_css_start");
extern const uint8_t _binary_style_css_end[]   asm("_binary_style_css_end");
extern const uint8_t _binary_app_js_start[] asm("_binary_app_js_start");
extern const uint8_t _binary_app_js_end[]   asm("_binary_app_js_end");

/*
 * WARNING: Default credentials are admin/admin123.
 * These MUST be changed before any production deployment.
 * This is a local-prototype login system, not internet-facing security.
 */
#define DEFAULT_USERNAME "admin"
#define DEFAULT_PASSWORD "admin123"

/* --------------- Helpers --------------- */

/* Extract session token from Cookie header.
   WARNING: This is a local-prototype auth scheme.
   Session tokens are random but transmitted as plain cookies.
   Not secure against network sniffing on open Wi-Fi. */
static bool get_session_from_request(httpd_req_t *req, char *token_out, size_t token_len)
{
    size_t buf_len = httpd_req_get_hdr_value_len(req, "Cookie");
    if (buf_len <= 0) return false;

    char *cookie_buf = malloc(buf_len + 1);
    if (!cookie_buf) return false;

    if (httpd_req_get_hdr_value_str(req, "Cookie", cookie_buf, buf_len + 1) != ESP_OK) {
        free(cookie_buf);
        return false;
    }

    /* Simple parse: find "session=" */
    const char *start = strstr(cookie_buf, "session=");
    if (start) {
        start += 8; /* skip "session=" */
        const char *end = strchr(start, ';');
        size_t len = end ? (size_t)(end - start) : strlen(start);
        if (len >= token_len) len = token_len - 1;
        memcpy(token_out, start, len);
        token_out[len] = '\0';
        free(cookie_buf);
        return true;
    }
    free(cookie_buf);
    return false;
}

/* Auth check middleware - returns true if session is valid */
static bool require_auth(httpd_req_t *req)
{
    char token[SESSION_TOKEN_LEN] = {0};
    if (!get_session_from_request(req, token, sizeof(token))) return false;
    return session_validate(token);
}

/* Send JSON response */
static esp_err_t send_json(httpd_req_t *req, const char *json, const char *status)
{
    httpd_resp_set_type(req, "application/json");
    httpd_resp_set_status(req, status);
    httpd_resp_send(req, json, strlen(json));
    return ESP_OK;
}

/* Scan context for non-blocking callback */
typedef struct {
    SemaphoreHandle_t sem;
    wifi_scan_entry_t entries[WIFI_SCAN_MAX];
    int count;
} wifi_scan_ctx_t;

static void scan_complete_cb(void *user_ctx, wifi_scan_entry_t *entries, int count)
{
    wifi_scan_ctx_t *ctx = (wifi_scan_ctx_t *)user_ctx;
    ctx->count = (count > WIFI_SCAN_MAX) ? WIFI_SCAN_MAX : count;
    if (ctx->count > 0) {
        memcpy(ctx->entries, entries, ctx->count * sizeof(wifi_scan_entry_t));
    }
    xSemaphoreGive(ctx->sem);
}

/* Send a static embedded file */
static esp_err_t serve_static(httpd_req_t *req, const uint8_t *start, const uint8_t *end,
                              const char *mime_type)
{
    size_t len = (size_t)(end - start);
    httpd_resp_set_type(req, mime_type);
    httpd_resp_send(req, (const char *)start, len);
    return ESP_OK;
}

/* --------------- Route Handlers --------------- */

/* GET / - redirect based on auth status */
static esp_err_t handle_root(httpd_req_t *req)
{
    char token[SESSION_TOKEN_LEN] = {0};
    if (get_session_from_request(req, token, sizeof(token)) && session_validate(token)) {
        httpd_resp_set_status(req, "302 Found");
        httpd_resp_set_hdr(req, "Location", "/dashboard");
        httpd_resp_send(req, NULL, 0);
    } else {
        httpd_resp_set_status(req, "302 Found");
        httpd_resp_set_hdr(req, "Location", "/login");
        httpd_resp_send(req, NULL, 0);
    }
    return ESP_OK;
}

/* GET /login */
static esp_err_t handle_get_login(httpd_req_t *req)
{
    return serve_static(req,
        _binary_login_html_start, _binary_login_html_end,
        "text/html; charset=utf-8");
}

/* GET /dashboard - protected */
static esp_err_t handle_get_dashboard(httpd_req_t *req)
{
    if (!require_auth(req)) {
        httpd_resp_set_status(req, "302 Found");
        httpd_resp_set_hdr(req, "Location", "/login");
        httpd_resp_send(req, NULL, 0);
        return ESP_OK;
    }
    return serve_static(req,
        _binary_dashboard_html_start, _binary_dashboard_html_end,
        "text/html; charset=utf-8");
}

/* GET /wifi - protected */
static esp_err_t handle_get_wifi(httpd_req_t *req)
{
    if (!require_auth(req)) {
        httpd_resp_set_status(req, "302 Found");
        httpd_resp_set_hdr(req, "Location", "/login");
        httpd_resp_send(req, NULL, 0);
        return ESP_OK;
    }
    return serve_static(req,
        _binary_wifi_html_start, _binary_wifi_html_end,
        "text/html; charset=utf-8");
}

/* GET /style.css */
static esp_err_t handle_style_css(httpd_req_t *req)
{
    return serve_static(req,
        _binary_style_css_start, _binary_style_css_end,
        "text/css; charset=utf-8");
}

/* GET /app.js */
static esp_err_t handle_app_js(httpd_req_t *req)
{
    return serve_static(req,
        _binary_app_js_start, _binary_app_js_end,
        "application/javascript; charset=utf-8");
}

/* POST /api/login */
static esp_err_t handle_api_login(httpd_req_t *req)
{
    char body[256] = {0};
    int ret = httpd_req_recv(req, body, sizeof(body) - 1);
    if (ret <= 0) {
        return send_json(req, "{\"ok\":false,\"error\":\"empty_body\"}", "401 Unauthorized");
    }
    body[ret] = '\0';

    char username[64] = {0};
    char password[64] = {0};

    const char *user_start = strstr(body, "username=");
    if (user_start) {
        user_start += 9;
        const char *user_end = strchr(user_start, '&');
        size_t len = user_end ? (size_t)(user_end - user_start) : strlen(user_start);
        if (len > 63) len = 63;
        memcpy(username, user_start, len);

        const char *pass_start = strstr(body, "password=");
        if (pass_start) {
            pass_start += 9;
            const char *pass_end = strchr(pass_start, '&');
            len = pass_end ? (size_t)(pass_end - pass_start) : strlen(pass_start);
            if (len > 63) len = 63;
            memcpy(password, pass_start, len);
        }
    } else {
        cJSON *root = cJSON_Parse(body);
        if (root) {
            cJSON *u = cJSON_GetObjectItem(root, "username");
            cJSON *p = cJSON_GetObjectItem(root, "password");
            if (u && cJSON_IsString(u)) {
                strncpy(username, u->valuestring, sizeof(username) - 1);
            }
            if (p && cJSON_IsString(p)) {
                strncpy(password, p->valuestring, sizeof(password) - 1);
            }
            cJSON_Delete(root);
        }
    }

    if (strlen(username) == 0 || strlen(password) == 0) {
        return send_json(req, "{\"ok\":false,\"error\":\"missing_fields\"}", "401 Unauthorized");
    }

    if (strcmp(username, DEFAULT_USERNAME) != 0 || strcmp(password, DEFAULT_PASSWORD) != 0) {
        ESP_LOGW(TAG, "Login failed");
        return send_json(req, "{\"ok\":false,\"error\":\"invalid_credentials\"}", "401 Unauthorized");
    }

    char token[SESSION_TOKEN_LEN] = {0};
    if (!session_create(username, token)) {
        return send_json(req, "{\"ok\":false,\"error\":\"session_error\"}", "500 Internal Server Error");
    }

    cJSON *resp = cJSON_CreateObject();
    cJSON_AddBoolToObject(resp, "ok", true);
    cJSON_AddStringToObject(resp, "token", token);
    cJSON_AddStringToObject(resp, "username", username);
    char *json_str = cJSON_PrintUnformatted(resp);
    cJSON_Delete(resp);

    char cookie[128];
    snprintf(cookie, sizeof(cookie), "session=%s; Path=/", token);
    httpd_resp_set_hdr(req, "Set-Cookie", cookie);

    ESP_LOGI(TAG, "Login success");
    esp_err_t result = send_json(req, json_str, "200 OK");
    free(json_str);
    return result;
}

/* POST /api/logout */
static esp_err_t handle_api_logout(httpd_req_t *req)
{
    char token[SESSION_TOKEN_LEN] = {0};
    if (get_session_from_request(req, token, sizeof(token))) {
        session_destroy(token);
    }

    /* Clear cookie */
    httpd_resp_set_hdr(req, "Set-Cookie",
        "session=; Path=/; Max-Age=0");

    return send_json(req, "{\"ok\":true}", "200 OK");
}

/* GET /api/wifi/scan - protected, returns JSON scan results */
static esp_err_t handle_api_wifi_scan(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", "401 Unauthorized");
    }

    wifi_scan_ctx_t ctx;
    ctx.sem = xSemaphoreCreateBinary();
    ctx.count = 0;
    if (!ctx.sem) {
        return send_json(req, "{\"ok\":false,\"error\":\"memory\"}", "500 Internal Server Error");
    }

    if (!wifi_manager_scan(&ctx, scan_complete_cb)) {
        vSemaphoreDelete(ctx.sem);
        return send_json(req, "{\"ok\":false,\"error\":\"scan_failed\"}", "200 OK");
    }

    if (xSemaphoreTake(ctx.sem, pdMS_TO_TICKS(5000)) != pdTRUE) {
        vSemaphoreDelete(ctx.sem);
        return send_json(req, "{\"ok\":false,\"error\":\"scan_timeout\"}", "200 OK");
    }
    vSemaphoreDelete(ctx.sem);

    cJSON *root = cJSON_CreateObject();
    cJSON_AddBoolToObject(root, "ok", true);
    cJSON *arr = cJSON_AddArrayToObject(root, "networks");
    for (int i = 0; i < ctx.count; i++) {
        cJSON *item = cJSON_CreateObject();
        cJSON_AddStringToObject(item, "ssid", ctx.entries[i].ssid);
        cJSON_AddNumberToObject(item, "rssi", ctx.entries[i].rssi);
        cJSON_AddStringToObject(item, "auth", ctx.entries[i].auth);
        cJSON_AddNumberToObject(item, "channel", ctx.entries[i].channel);
        cJSON_AddItemToArray(arr, item);
    }

    char *json_str = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, json_str, strlen(json_str));
    free(json_str);

    return ESP_OK;
}

/* POST /api/wifi/connect - protected, connect to given SSID */
static esp_err_t handle_api_wifi_connect(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", "401 Unauthorized");
    }

    char body[512] = {0};
    int ret = httpd_req_recv(req, body, sizeof(body) - 1);
    if (ret <= 0) {
        return send_json(req, "{\"ok\":false,\"error\":\"empty_body\"}", "200 OK");
    }
    body[ret] = '\0';

    char ssid[64] = {0};
    char password[64] = {0};

    cJSON *root = cJSON_Parse(body);
    if (root) {
        cJSON *s = cJSON_GetObjectItem(root, "ssid");
        cJSON *p = cJSON_GetObjectItem(root, "password");
        if (s && cJSON_IsString(s)) {
            strncpy(ssid, s->valuestring, sizeof(ssid) - 1);
        }
        if (p && cJSON_IsString(p)) {
            strncpy(password, p->valuestring, sizeof(password) - 1);
        }
        cJSON_Delete(root);
    }

    if (strlen(ssid) == 0) {
        return send_json(req, "{\"ok\":false,\"error\":\"missing_ssid\"}", "200 OK");
    }

    if (!wifi_manager_connect_sta(ssid, password)) {
        return send_json(req, "{\"ok\":false,\"error\":\"connect_error\"}", "200 OK");
    }

    vTaskDelay(pdMS_TO_TICKS(5000));

    cJSON *resp = cJSON_CreateObject();
    if (wifi_manager_is_sta_connected()) {
        cJSON_AddBoolToObject(resp, "ok", true);
        cJSON_AddStringToObject(resp, "ssid", wifi_manager_get_sta_ssid());
        cJSON_AddStringToObject(resp, "ip", wifi_manager_get_sta_ip());
    } else {
        cJSON_AddBoolToObject(resp, "ok", false);
        cJSON_AddStringToObject(resp, "error", "connection_failed");
        cJSON_AddStringToObject(resp, "ssid", ssid);
    }
    char *json_str = cJSON_PrintUnformatted(resp);
    cJSON_Delete(resp);
    esp_err_t result = send_json(req, json_str, "200 OK");
    free(json_str);
    return result;
}

/* GET /api/status - protected, return device status JSON */
static esp_err_t handle_api_status(httpd_req_t *req)
{
    if (!require_auth(req)) {
        return send_json(req, "{\"ok\":false,\"error\":\"unauthorized\"}", "401 Unauthorized");
    }

    bool ap_up = wifi_manager_is_ap_enabled();

    cJSON *root = cJSON_CreateObject();
    cJSON_AddBoolToObject(root, "ok", true);
    cJSON_AddBoolToObject(root, "ap_enabled", ap_up);
    cJSON_AddStringToObject(root, "ap_ip", ap_up ? wifi_manager_get_ap_ip() : "");
    cJSON_AddBoolToObject(root, "sta_connected", wifi_manager_is_sta_connected());
    cJSON_AddStringToObject(root, "sta_ip", wifi_manager_is_sta_connected() ? wifi_manager_get_sta_ip() : "");
    cJSON_AddStringToObject(root, "sta_ssid", wifi_manager_is_sta_connected() ? wifi_manager_get_sta_ssid() : "");
    cJSON_AddNumberToObject(root, "uptime_ms", (double)wifi_manager_get_uptime_ms());
    cJSON_AddNumberToObject(root, "free_heap", (double)wifi_manager_get_free_heap());

    char *json_str = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    esp_err_t result = send_json(req, json_str, "200 OK");
    free(json_str);
    return result;
}

/* --------------- Server Start --------------- */

bool web_server_start(void)
{
    httpd_handle_t server = NULL;
    httpd_config_t config = HTTPD_DEFAULT_CONFIG();
    config.max_uri_handlers = 16;
    config.lru_purge_enable = true;

    if (httpd_start(&server, &config) != ESP_OK) {
        ESP_LOGE(TAG, "Failed to start HTTP server");
        return false;
    }

    const httpd_uri_t routes[] = {
        { .uri = "/",              .method = HTTP_GET,  .handler = handle_root,           .user_ctx = NULL },
        { .uri = "/login",         .method = HTTP_GET,  .handler = handle_get_login,      .user_ctx = NULL },
        { .uri = "/dashboard",     .method = HTTP_GET,  .handler = handle_get_dashboard,  .user_ctx = NULL },
        { .uri = "/wifi",          .method = HTTP_GET,  .handler = handle_get_wifi,       .user_ctx = NULL },
        { .uri = "/style.css",     .method = HTTP_GET,  .handler = handle_style_css,      .user_ctx = NULL },
        { .uri = "/app.js",        .method = HTTP_GET,  .handler = handle_app_js,         .user_ctx = NULL },
        { .uri = "/api/login",     .method = HTTP_POST, .handler = handle_api_login,      .user_ctx = NULL },
        { .uri = "/api/logout",    .method = HTTP_POST, .handler = handle_api_logout,     .user_ctx = NULL },
        { .uri = "/api/wifi/scan", .method = HTTP_GET,  .handler = handle_api_wifi_scan,  .user_ctx = NULL },
        { .uri = "/api/wifi/connect", .method = HTTP_POST, .handler = handle_api_wifi_connect, .user_ctx = NULL },
        { .uri = "/api/status",    .method = HTTP_GET,  .handler = handle_api_status,     .user_ctx = NULL },
    };

    for (int i = 0; i < sizeof(routes) / sizeof(routes[0]); i++) {
        httpd_register_uri_handler(server, &routes[i]);
    }

    ESP_LOGI(TAG, "HTTP server started on port %d", config.server_port);
    return true;
}
