#pragma once

/*
 * Template-level configuration.
 *
 * When using this repository as a base for another project, start here:
 * change product names, AP SSID, mDNS hostname, credentials, and limits in
 * this file before touching the Wi-Fi or web-server internals.
 */

#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

#define APP_TEMPLATE_NAME                  "Fish Pump Relay Timer Control"
#define APP_TEMPLATE_FIRMWARE_VERSION      "v0.1.0"
#define APP_TEMPLATE_PHASE_LABEL           "Wi-Fi Setup and Control Dashboard"

#define APP_TEMPLATE_AP_SSID               "FishPump-Setup"
#define APP_TEMPLATE_AP_CHANNEL            1
#define APP_TEMPLATE_AP_MAX_CONN           4
#define APP_TEMPLATE_WIFI_SCAN_MAX         20
#define APP_TEMPLATE_WIFI_MAX_TX_POWER_QDBM 80
#define APP_TEMPLATE_WIFI_SCAN_ACTIVE_MIN_MS 30
#define APP_TEMPLATE_WIFI_SCAN_ACTIVE_MAX_MS 60
#define APP_TEMPLATE_WIFI_SCAN_HOME_DWELL_MS 30

#define APP_TEMPLATE_MDNS_HOSTNAME         "fish-pump"
#define APP_TEMPLATE_MDNS_INSTANCE_NAME    "Fish Pump Dashboard"

#define APP_TEMPLATE_DEFAULT_USERNAME      "admin"
#define APP_TEMPLATE_DEFAULT_PASSWORD      "admin123"

#define APP_TEMPLATE_SESSION_MAX_AGE_SEC   0
#define APP_TEMPLATE_LOGIN_RATE_LIMIT_MAX  5
#define APP_TEMPLATE_LOGIN_RATE_LIMIT_SEC  30

#define APP_TEMPLATE_AP_STOP_TMO_DEFAULT_MS 60000
#define APP_TEMPLATE_AP_AUTO_STOP_DEFAULT   true

#define APP_TEMPLATE_HTTP_MAX_URI_HANDLERS 32
#define APP_TEMPLATE_HTTP_MAX_OPEN_SOCKETS 7
#define APP_TEMPLATE_HTTP_RECV_TIMEOUT_SEC 8
#define APP_TEMPLATE_HTTP_SEND_TIMEOUT_SEC 2
#define APP_TEMPLATE_HTTP_STATIC_CHUNK_BYTES 2048
#define APP_TEMPLATE_HTTP_STATIC_MAX_DURATION_MS 6000
#define APP_TEMPLATE_HTTP_KEEP_ALIVE_IDLE_SEC 5
#define APP_TEMPLATE_HTTP_KEEP_ALIVE_INTERVAL_SEC 3
#define APP_TEMPLATE_HTTP_KEEP_ALIVE_COUNT 3
#define APP_TEMPLATE_HTTP_SLOW_REQUEST_MS  1000
#define APP_TEMPLATE_MAIN_WDT_TIMEOUT_MS   10000
#define APP_TEMPLATE_STATUS_LOG_INTERVALS  6

#define APP_TEMPLATE_PUMP_FLOAT_GPIO        32
#define APP_TEMPLATE_PUMP_FLOAT_ACTIVE_LOW  true
#define APP_TEMPLATE_PUMP_RELAY_GPIO        26
#define APP_TEMPLATE_PUMP_RELAY_ACTIVE_LOW  true

#define APP_TEMPLATE_HW_DEFAULT_FLOAT_GPIO              32
#define APP_TEMPLATE_HW_DEFAULT_PUMP_RELAY1_GPIO        26
#define APP_TEMPLATE_HW_DEFAULT_PUMP_RELAY2_GPIO        27
#define APP_TEMPLATE_HW_DEFAULT_DS18B20_GPIO            33
#define APP_TEMPLATE_HW_DEFAULT_COOLING_RELAY_GPIO      25
#define APP_TEMPLATE_HW_DEFAULT_PUMP_RELAY1_ACTIVE_LOW  true
#define APP_TEMPLATE_HW_DEFAULT_PUMP_RELAY2_ACTIVE_LOW  true
#define APP_TEMPLATE_HW_DEFAULT_COOLING_RELAY_ACTIVE_LOW true
#define APP_TEMPLATE_PUMP_TIMER_START_ON                true
#define APP_TEMPLATE_COOLING_THRESHOLD_C_X10            300
#define APP_TEMPLATE_COOLING_HYSTERESIS_C_X10           10
#define APP_TEMPLATE_COOLING_AUTO_ENABLE_DEFAULT        false
#define APP_TEMPLATE_COOLING_TEST_TIMEOUT_SEC           10
#define APP_TEMPLATE_COOLING_MIN_OFF_SEC                10

#define APP_TEMPLATE_PUMP_TIMER1_ON_SEC     20
#define APP_TEMPLATE_PUMP_TIMER1_OFF_SEC    60
#define APP_TEMPLATE_PUMP_TIMER2_ON_SEC     10
#define APP_TEMPLATE_PUMP_TIMER2_OFF_SEC    180
#define APP_TEMPLATE_PUMP_TIMER_MIN_SEC     5
#define APP_TEMPLATE_PUMP_TIMER_MAX_SEC     86400
#define APP_TEMPLATE_PUMP_AUTO_START_DEFAULT false
#define APP_TEMPLATE_PUMP_FLOAT_DEBOUNCE_MS 100

#ifdef __cplusplus
}
#endif
