# Generate secrets.h with a random AES-256 key for OTA encryption.
# Run this once per deployment. Keep the generated key safe.

$SecretsPath = Join-Path $PSScriptRoot "..\components\app_config\secrets.h"

if (Test-Path $SecretsPath) {
    Write-Host "secrets.h already exists at $SecretsPath - delete it first if you want a new key." -ForegroundColor Yellow
    exit 0
}

$bytes = New-Object byte[] 32
[System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
$hex = ($bytes | ForEach-Object { $_.ToString("X2") }) -join ""

$content = @"
# pragma once
// OTA Encryption Key - generated by scripts/generate_secrets.ps1
// DO NOT COMMIT THIS FILE. It is listed in .gitignore.
// Keep a backup of this key: losing it means OTA encrypted binaries
// produced with this key cannot be decrypted by this device.
#define APP_CONFIG_OTA_ENCRYPTION_KEY `"$hex`"
"@

Set-Content -Path $SecretsPath -Value $content -Encoding UTF8
Write-Host "secrets.h generated at $SecretsPath" -ForegroundColor Green
Write-Host "Key: $hex" -ForegroundColor Cyan
Write-Host "IMPORTANT: Back up this key - store in password manager or offline." -ForegroundColor Red
